<!-- This code was generated by Builder.io -->
<template>
  <header class="calendar-header">
    <h2 class="calendar-title">MY Calender</h2>
    <div class="action-buttons">
      <button class="action-btn book-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b04ac40f5d56c044d9a304e430e72fbac4a33454a9f18e2ea81484a5d1ac6109?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="btn-icon"
        />
        製本依頼
      </button>
      <button class="action-btn pdf-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9926cc608fa76d2fdfbd0bc22d8686958007548afc4645db8652b50474ab0454?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="btn-icon"
        />
        PDF出力
      </button>
    </div>
    <div class="year-selector">
      <span class="year">2025</span>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/31a90bc41ae369594ec5baafbb3f1cdec020a3a5254b02002733d7a0a317acbf?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Year selector"
        class="selector-icon"
      />
    </div>
    <nav class="month-nav">
      <a href="#" class="month-link">１月</a>
      <a href="#" class="month-link">２月</a>
      <a href="#" class="month-link">３月</a>
      <a href="#" class="month-link">４月</a>
      <a href="#" class="month-link active">５月</a>
      <a href="#" class="month-link">６月</a>
      <a href="#" class="month-link">７月</a>
      <a href="#" class="month-link">８月</a>
      <a href="#" class="month-link">９月</a>
      <a href="#" class="month-link">１０月</a>
      <a href="#" class="month-link">１１月</a>
      <a href="#" class="month-link">１２月</a>
    </nav>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarHeader",
});
</script>

<style scoped>
.calendar-header {
  font-family: "Noto Sans", sans-serif;
  color: #fff;
  margin-bottom: 10px;
}

.calendar-title {
  font-size: 40px;
  font-weight: 700;
  margin: 0 0 10px;
}

.action-buttons {
  display: flex;
  gap: 14px;
  margin-bottom: 10px;
}

.action-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  background-color: #fff;
  color: #000;
  border: none;
  border-radius: 50px;
  padding: 10px 30px;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
}

.btn-icon {
  width: 20px;
  height: 20px;
}

.year-selector {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #fff;
  border: 1px solid #a1a1a1;
  border-radius: 4px;
  padding: 5px 8px;
  width: 151px;
  margin-bottom: 10px;
}

.year {
  font-size: 16px;
  color: #000;
}

.selector-icon {
  width: 12px;
  height: 8px;
}

.month-nav {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.month-link {
  color: #757575;
  text-decoration: none;
  font-size: 24px;
}

.month-link.active {
  color: #000;
  border-bottom: 5px solid #a7cdfe;
  padding-bottom: 5px;
}

@media (max-width: 991px) {
  .action-buttons,
  .month-nav {
    flex-direction: column;
    align-items: flex-start;
  }

  .action-btn,
  .month-link {
    margin-bottom: 10px;
  }
}
</style>
