<!-- This code was generated by Builder.io -->
<template>
  <div class="calendar-settings">
    <h2 class="settings-title">MYカレンダー設定</h2>
    <div class="year-selector">
      <span class="year">2025</span>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/31a90bc41ae369594ec5baafbb3f1cdec020a3a5254b02002733d7a0a317acbf?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Year selector"
        class="selector-icon"
      />
    </div>
    <span class="year-label">年</span>

    <h3 class="layout-title">レイアウト</h3>
    <div class="layout-options">
      <button class="layout-option" aria-label="Layout option 1">
        <div class="layout-circle"></div>
        <div class="layout-preview">
          <div class="preview-header"></div>
        </div>
      </button>
      <button class="layout-option" aria-label="Layout option 2">
        <div class="layout-circle"></div>
        <div class="layout-preview">
          <div class="preview-left"></div>
          <div class="preview-right">
            <div class="preview-top"></div>
            <div class="preview-bottom"></div>
          </div>
        </div>
      </button>
      <button class="layout-option" aria-label="Layout option 3">
        <div class="layout-circle"></div>
        <div class="layout-preview">
          <div class="preview-top"></div>
          <div class="preview-bottom">
            <div class="preview-left"></div>
            <div class="preview-right"></div>
          </div>
        </div>
      </button>
      <button class="layout-option active" aria-label="Layout option 4">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c07c66ff10ea787a4ee264eaee8dd32b216d365bbf7cbdc57ab6d1ffa0d616c2?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="layout-icon"
        />
        <div class="layout-preview">
          <div class="preview-content">
            <div class="preview-line"></div>
            <div class="preview-line"></div>
            <div class="preview-line"></div>
          </div>
        </div>
      </button>
    </div>
    <div class="scroll-indicator"></div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarSettings",
});
</script>

<style scoped>
.calendar-settings {
  border-radius: 20px;
  background-color: rgba(255, 255, 255, 0.9);
  padding: 31px 15px 18px;
  font-family: "Noto Sans", sans-serif;
}

.settings-title {
  color: #000;
  text-align: center;
  font-weight: 700;
  font-size: 16px;
  margin: 0 0 30px;
}

.year-selector {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #fff;
  border: 1px solid #a1a1a1;
  border-radius: 4px;
  padding: 5px 8px;
  margin-bottom: 5px;
}

.year {
  font-size: 16px;
  color: #000;
}

.selector-icon {
  width: 12px;
  height: 8px;
}

.year-label {
  display: block;
  text-align: right;
  font-size: 16px;
  color: #000;
  margin-bottom: 13px;
}

.layout-title {
  color: #000;
  font-size: 14px;
  font-weight: 500;
  margin: 0 0 12px;
}

.layout-options {
  display: flex;
  gap: 10px;
  margin-bottom: 23px;
}

.layout-option {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #fff;
  border: 1px solid #a1a1a1;
  border-radius: 4px;
  padding: 5px;
  cursor: pointer;
}

.layout-circle {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  border: 1px solid #d9d9d9;
  margin-bottom: 12px;
}

.layout-preview {
  width: 50px;
  height: 36px;
  border: 1px solid #000;
}

.preview-header,
.preview-left,
.preview-right,
.preview-top,
.preview-bottom {
  background-color: #d9d9d9;
  border: 1px solid #000;
}

.layout-icon {
  width: 10px;
  height: 10px;
  margin-bottom: 12px;
}

.preview-content {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 2px;
}

.preview-line {
  height: 2px;
  background-color: #000;
}

.scroll-indicator {
  width: 6px;
  height: 112px;
  background-color: rgba(217, 217, 217, 0.5);
  border-radius: 10px;
  margin-left: auto;
}

.active {
  border: 2px solid #03a6c7;
}
</style>
