<!-- This code was generated by Builder.io -->
<template>
  <div class="calendar-body">
    <aside class="sidebar">
      <nav class="sidebar-nav">
        <a href="#" class="nav-item active">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d09d4b0566a31eeb667160e225c8d4ae50e7111de1ea57ffc78c0495dce3d18?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>MYストーリー</span>
        </a>
        <a href="#" class="nav-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>ブックマーク</span>
        </a>
        <a href="#" class="nav-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>フォロー</span>
        </a>
        <a href="#" class="nav-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/19bbaac8620bdb0884d9d649f185d08609cb2095446939daab2a4edae9e2d89e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>MYカレンダー</span>
        </a>
        <a href="#" class="nav-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb327d2d47b0f6866125a421eba8bbefcb1ff345434debebc120bb550d7b1065?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>MY新聞</span>
        </a>
        <a href="#" class="nav-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/44cee03747ea9736ef6c8efd074e5f8b04dc3372d2af50c30a133309537242f7?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="nav-icon"
          />
          <span>設定</span>
        </a>
      </nav>
    </aside>
    <main class="calendar-content">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/82656000abb09ff09808260ff55586f41ad1484fd813e1e5713a6d38be071c92?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Calendar background"
        class="calendar-background"
      />
      <article class="calendar-story">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3b0c4cbe0a0c3fa80b4a6675b5b6f42e7e6db65e4632e8734bf52137d38880ef?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="story-image"
        />
        <div class="story-content">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/aedefa38332a4366f40f0d0a71fcf94ba86db18ce0c88383c3a11c2a868dabc7?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt=""
            class="story-icon"
          />
          <h3 class="story-title">スカイダイビングへの挑戦</h3>
          <p class="story-text">
            人生最高の度胸試しは私にとって新たな価値観をもたらした。<br />
            上空1000ｍからみた地上は何もかもが小さくみえた日常の些細なことなどすべて忘れるような光景だ<br />
            その中へまさにこれから飛び込もうとしている<br />
            胸の高鳴りを抑えることはとてもできない
          </p>
        </div>
      </article>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarBody",
});
</script>

<style scoped>
.calendar-body {
  display: flex;
  background-color: #fff;
  border-radius: 10px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  overflow: hidden;
}

.sidebar {
  width: 300px;
  background-color: rgba(255, 255, 255, 0.5);
  padding: 20px;
}

.sidebar-nav {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.nav-item {
  display: flex;
  align-items: center;
  gap: 10px;
  text-decoration: none;
  color: #000;
  font-weight: 700;
  font-size: 16px;
  font-family: "Noto Sans", sans-serif;
}

.nav-icon {
  width: 24px;
  height: 24px;
}

.calendar-content {
  flex: 1;
  position: relative;
  overflow: hidden;
}

.calendar-background {
  width: 100%;
  height: auto;
}

.calendar-story {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: rgba(255, 255, 255, 0.8);
  padding: 20px;
  display: flex;
  gap: 20px;
}

.story-image {
  width: 100px;
  height: 100px;
  object-fit: cover;
}

.story-content {
  flex: 1;
}

.story-icon {
  width: 24px;
  height: 24px;
  margin-bottom: 10px;
}

.story-title {
  font-size: 24px;
  font-weight: 700;
  margin: 0 0 10px;
  color: #fff;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px rgba(0, 0, 0, 0.15);
}

.story-text {
  font-size: 12px;
  color: #fff;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px rgba(0, 0, 0, 0.15);
  line-height: 1.5;
}

@media (max-width: 991px) {
  .calendar-body {
    flex-direction: column;
  }

  .sidebar {
    width: 100%;
  }

  .calendar-story {
    flex-direction: column;
  }
}
</style>
