<!-- This code was generated by Builder.io -->
<template>
  <div class="my-calendar-page">
    <header class="header">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt=""
        class="background-image"
      />
      <div class="header-content">
        <div class="logo-container">
          <h1 class="logo">jiBUN-See</h1>
          <p class="tagline">みんなのストーリーを見てみよう</p>
        </div>
        <nav class="main-nav">
          <a href="#" class="nav-item">ホーム</a>
          <a href="#" class="nav-item">よく見られているストーリー</a>
          <a href="#" class="nav-item">サイトについて</a>
          <a href="#" class="nav-item">料金</a>
          <a href="#" class="nav-item">お問合せ</a>
          <a href="#" class="nav-item active">MYページ</a>
          <a href="#" class="nav-item logout-btn">ログアウト</a>
        </nav>
      </div>
    </header>

    <main class="main-content">
      <aside class="sidebar">
        <CalendarSettings />
      </aside>

      <section class="calendar-section">
        <CalendarHeader />
        <CalendarBody />
      </section>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import CalendarSettings from "./CalendarSettings.vue";
import CalendarHeader from "./CalendarHeader.vue";
import CalendarBody from "./CalendarBody.vue";

export default defineComponent({
  name: "MyCalendarPage",
  components: {
    CalendarSettings,
    CalendarHeader,
    CalendarBody,
  },
});
</script>

<style scoped>
.my-calendar-page {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.header {
  position: relative;
  width: 100%;
}

.background-image {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.header-content {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 15px 41px 9px;
  background-color: rgba(255, 255, 255, 0.9);
}

.logo-container {
  display: flex;
  flex-direction: column;
}

.logo {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
  margin: 0;
}

.tagline {
  color: #363636;
  text-align: center;
  font: 700 14px "Noto Sans", sans-serif;
  margin: 4px 0 0;
}

.main-nav {
  display: flex;
  align-items: center;
  gap: 29px;
}

.nav-item {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
  padding: 5px 0;
}

.nav-item.active {
  border-bottom: 5px solid #a7cdfe;
  padding: 10px 0;
}

.logout-btn {
  border: 3px solid #a7cdfe;
  border-radius: 50px;
  padding: 10px;
  font-weight: 700;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
}

.main-content {
  display: flex;
  margin-top: 27px;
  width: 100%;
  max-width: 1380px;
  align-self: center;
}

.sidebar {
  width: 24%;
}

.calendar-section {
  width: 76%;
  margin-left: 20px;
}

@media (max-width: 991px) {
  .header-content {
    flex-direction: column;
    padding: 15px 20px;
  }

  .main-nav {
    flex-direction: column;
    align-items: flex-start;
    gap: 10px;
    margin-top: 15px;
  }

  .main-content {
    flex-direction: column;
  }

  .sidebar,
  .calendar-section {
    width: 100%;
    margin-left: 0;
  }

  .sidebar {
    margin-bottom: 20px;
  }
}
</style>
