<!-- This code was generated by Builder.io -->
<template>
  <header class="site-header">
    <div class="header-content">
      <div class="logo-container">
        <h1 class="site-title">jiBUN-See</h1>
        <p class="site-subtitle">みんなのストーリーを見てみよう</p>
      </div>
      <nav class="main-navigation">
        <ul class="nav-list">
          <li><a href="#" class="nav-item">ホーム</a></li>
          <li><a href="#" class="nav-item">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-item">サイトについて</a></li>
          <li><a href="#" class="nav-item">料金</a></li>
          <li><a href="#" class="nav-item">お問合せ</a></li>
          <li><a href="#" class="nav-item active">MYページ</a></li>
        </ul>
      </nav>
      <button class="logout-button" @click="logout">ログアウト</button>
    </div>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Header",
  methods: {
    logout() {
      // Implement logout functionality
      console.log("Logout clicked");
    },
  },
});
</script>

<style scoped>
.site-header {
  border-radius: 0;
}

.header-content {
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  align-items: center;
  gap: 29px;
  padding: 15px 41px 9px;
}

.logo-container {
  display: flex;
  flex-direction: column;
}

.site-title {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
  margin: 0;
}

.site-subtitle {
  color: #363636;
  text-align: center;
  margin-top: 4px;
  font: 700 14px "Noto Sans", sans-serif;
}

.main-navigation {
  flex-grow: 1;
}

.nav-list {
  display: flex;
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.nav-item {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
  padding: 5px 0;
}

.nav-item.active {
  border-bottom: 5px solid #a7cdfe;
  padding: 10px 0;
}

.logout-button {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  color: #000;
  padding: 10px;
  font: 700 16px "Noto Sans", sans-serif;
  cursor: pointer;
}

@media (max-width: 991px) {
  .header-content {
    flex-wrap: wrap;
    padding: 15px 20px;
  }

  .nav-list {
    flex-wrap: wrap;
  }

  .nav-item {
    margin-right: 10px;
    margin-bottom: 5px;
  }
}
</style>
