<!-- This code was generated by Builder.io -->
<template>
  <section class="vertical-stripes">
    <div class="stripes-container">
      <div class="stripe" v-for="index in 5" :key="index"></div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "VerticalStripes",
});
</script>

<style scoped>
.vertical-stripes {
  display: flex;
  max-width: 132px;
  flex-direction: column;
}

.stripes-container {
  background-color: rgba(255, 255, 255, 0.5);
  display: flex;
  width: 100%;
  flex-direction: column;
  padding: 110px 11px 50px;
}

.stripe {
  border-radius: 0;
  align-self: stretch;
  display: flex;
  height: 8px;
  width: 104px;
  margin: auto 0;
}

.stripe:nth-child(3) {
  height: 9px;
}
</style>
