<!-- This code was generated by Builder.io -->
<template>
  <div class="my-story-container">
    <header class="navigation-header">
      <nav class="nav-menu">
        <NavItem icon="story" label="MYストーリー" />
        <NavItem icon="bookmark" label="ブックマーク" />
        <NavItem icon="follow" label="フォロー" />
        <NavItem icon="calendar" label="MYカレンダー" />
        <NavItem icon="newspaper" label="MY新聞" />
        <NavItem icon="settings" label="設定" />
      </nav>
    </header>
    <main class="main-content">
      <h1 class="main-title">MY Story</h1>
      <div class="filter-options">
        <button class="filter-btn active">投稿日順</button>
        <button class="filter-btn">TimeLine</button>
      </div>
      <div class="range-selector">
        <span class="range-label">MIN</span>
        <div class="range-container">
          <label for="range-input" class="visually-hidden">表示範囲</label>
          <input
            type="range"
            id="range-input"
            class="range-input"
            min="0"
            max="100"
          />
        </div>
        <span class="range-label">MAX</span>
      </div>
      <article class="story-card">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e293edcac335ac66e3aee1b365da6f3688dfe50e77e8193094000cf08218b2e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt="Story featured image"
          class="story-image"
        />
        <div class="story-content">
          <h2 class="story-title">
            <time datetime="2023-11-25">11/25</time> 記事タイトル
          </h2>
          <p class="story-excerpt">
            実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との
            CC 人の（またはの、ます、著作。
          </p>
          <button class="details-btn">詳細</button>
        </div>
      </article>
      <section class="story-grid">
        <StoryGridItem
          image="https://cdn.builder.io/api/v1/image/assets/TEMP/3e293edcac335ac66e3aee1b365da6f3688dfe50e77e8193094000cf08218b2e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          date="11/25"
          title="記事タイトル"
        />
        <StoryGridItem
          image="https://cdn.builder.io/api/v1/image/assets/TEMP/d5c69736a6dfdef61bf42768ea4a95700c565f20a78ae723a8699bf57728fce6?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          date="11/25"
          title="記事タイトル"
        />
        <StoryGridItem
          image="https://cdn.builder.io/api/v1/image/assets/TEMP/bb65634a52f34ac0bbea8032d998a52e7871eeec7446bf8b9f6ef55baf9e5fc1?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          date="11/25"
          title="記事タイトル"
        />
      </section>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import NavItem from "./NavItem.vue";
import StoryGridItem from "./StoryGridItem.vue";

export default defineComponent({
  name: "MyStoryComponent",
  components: {
    NavItem,
    StoryGridItem,
  },
});
</script>

<style scoped>
.my-story-container {
  display: flex;
  max-width: 823px;
  flex-direction: column;
}

.navigation-header {
  width: 100%;
  margin-bottom: 10px;
}

.nav-menu {
  display: flex;
  border-radius: 10px;
  background-color: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
  justify-content: space-between;
  flex-wrap: wrap;
}

.main-content {
  width: 100%;
  padding-bottom: 20px;
}

.main-title {
  color: #fff;
  font: 700 40px "Noto Sans", sans-serif;
  margin-bottom: 12px;
}

.filter-options {
  display: flex;
  margin-bottom: 12px;
}

.filter-btn {
  color: #000;
  font: 700 16px "Noto Sans", sans-serif;
  padding: 10px 20px;
  width: 160px;
  border: none;
  background-color: rgba(255, 255, 255, 0.3);
}

.filter-btn.active {
  background-color: #fff;
}

.filter-btn:first-child {
  border-radius: 50px 0 0 50px;
}

.filter-btn:last-child {
  border-radius: 0 50px 50px 0;
}

.range-selector {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}

.range-label {
  color: #000;
  font: 400 10px "Inter", sans-serif;
}

.range-container {
  flex-grow: 1;
  margin: 0 11px;
}

.range-input {
  width: 100%;
}

.story-card {
  background-color: #fff;
  border-radius: 20px;
  overflow: hidden;
  margin-bottom: 10px;
}

.story-image {
  width: 100%;
  height: auto;
}

.story-content {
  padding: 10px 20px;
}

.story-title {
  font: 16px/40px "Fugaz One", sans-serif;
  margin-bottom: 10px;
}

.story-excerpt {
  font: 400 14px/18px "Noto Sans", sans-serif;
  margin-bottom: 10px;
}

.details-btn {
  display: block;
  width: 100%;
  padding: 8px 20px;
  background-color: #fff;
  border: none;
  border-radius: 10px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  font: 700 14px "Noto Sans", sans-serif;
  text-align: center;
  cursor: pointer;
}

.story-grid {
  display: flex;
  gap: 20px;
  padding-left: 25px;
}

@media (max-width: 991px) {
  .nav-menu,
  .main-content,
  .story-card,
  .story-grid {
    max-width: 100%;
  }

  .story-grid {
    flex-direction: column;
    padding-left: 20px;
  }
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
