<!-- This code was generated by Builder.io -->
<template>
  <div class="nav-item">
    <div class="icon-wrapper">
      <img
        :src="`http://b.io/ext_${iconIndex}-`"
        :alt="`${label} icon`"
        class="nav-icon"
      />
    </div>
    <span class="nav-label">{{ label }}</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "NavItem",
  props: {
    icon: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
    },
  },
  computed: {
    iconIndex(): number {
      const iconMap: { [key: string]: number } = {
        story: 1,
        bookmark: 2,
        follow: 3,
        calendar: 4,
        newspaper: 5,
        settings: 6,
      };
      return iconMap[this.icon] || 1;
    },
  },
});
</script>

<style scoped>
.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 5px 0;
}

.icon-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 30px;
  margin-bottom: 5px;
}

.nav-icon {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}

.nav-label {
  color: #000;
  font: 700 16px "Noto Sans", sans-serif;
  text-align: center;
}
</style>
