<!-- This code was generated by Builder.io -->
<template>
  <article class="story-grid-item">
    <img
      :src="image"
      :alt="`Story image for ${title}`"
      class="grid-item-image"
    />
    <div class="grid-item-content">
      <h3 class="grid-item-title">
        <time :datetime="formattedDate">{{ date }}</time>
        <br />{{ title }}
      </h3>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "StoryGridItem",
  props: {
    image: {
      type: String,
      required: true,
    },
    date: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
  },
  computed: {
    formattedDate(): string {
      const [month, day] = this.date.split("/");
      return `2023-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
    },
  },
});
</script>

<style scoped>
.story-grid-item {
  flex: 1;
  min-width: 201px;
  border-radius: 20px;
  overflow: hidden;
  background-color: #fff;
  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
}

.grid-item-image {
  width: 100%;
  height: auto;
  object-fit: cover;
}

.grid-item-content {
  padding: 10px;
}

.grid-item-title {
  color: #000;
  font: 400 16px/18px "Fugaz One", sans-serif;
}

@media (max-width: 991px) {
  .story-grid-item {
    margin-top: 30px;
  }
}
</style>
