<!-- This code was generated by Builder.io -->
<template>
  <main class="calendar-container">
    <header class="calendar-header">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/75a6bb10399e6b28f796f50baadb2d5643181e56bc2167a4ac9bbf1a9eda81bf?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Calendar header image 1"
        class="header-image"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/dd84c35c4df941fd2ff4d7892b20862619dcccb14ee35dc03a0413837483c81c?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Calendar header image 2"
        class="header-image"
      />
    </header>
    <section class="calendar-body">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1d032b8c2980adba2b8fc8dcc2b54d82fe14619d4b080abade8725582666ee86?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Calendar background"
        class="background-image"
      />
      <div class="calendar-content"></div>
    </section>
  </main>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarComponent",
});
</script>

<style scoped>
.calendar-container {
  transform: rotate(1.570796370506285rad);
  background-color: #fff;
  display: flex;
  max-width: 420px;
  flex-direction: column;
  overflow: hidden;
}

.calendar-header {
  display: flex;
}

.header-image {
  object-fit: contain;
  object-position: center;
  max-width: 100%;
}

.header-image:first-child {
  aspect-ratio: 2.4;
  width: 214px;
}

.header-image:last-child {
  aspect-ratio: 2.31;
  width: 206px;
}

.calendar-body {
  display: flex;
  flex-direction: column;
  position: relative;
  min-height: 208px;
  width: 100%;
  padding-bottom: 88px;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.calendar-content {
  position: relative;
  background-color: rgba(255, 255, 255, 0.5);
  display: flex;
  min-height: 120px;
  width: 100%;
}
</style>
