<!-- This code was generated by Builder.io -->
<template>
  <section class="calendar-container">
    <div class="calendar-columns">
      <div class="calendar-column">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8faeef8a87df9a65ce739afa7b0e6418264689a172a8d09d46a757731a848785?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          class="calendar-image"
          alt="Calendar image 1"
        />
      </div>
      <div class="calendar-column">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/7940043d117a3bd7ac712c0187286aec60f6142162cf111df067626edaf4917e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          class="calendar-image calendar-image-secondary"
          alt="Calendar image 2"
        />
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarComponent",
});
</script>

<style scoped>
.calendar-container {
  transform: rotate(1.570796370506285rad);
  background-color: #fff;
  max-width: 420px;
  overflow: hidden;
}

.calendar-columns {
  display: flex;
  gap: 20px;
}

.calendar-column {
  display: flex;
  flex-direction: column;
}

.calendar-column:first-child {
  width: 54%;
}

.calendar-column:last-child {
  width: 46%;
}

.calendar-image {
  aspect-ratio: 0.77;
  object-fit: contain;
  object-position: center;
  width: 100%;
}

.calendar-image-secondary {
  aspect-ratio: 1.35;
  width: 192px;
  max-width: 100%;
}

@media (max-width: 991px) {
  .calendar-columns {
    flex-direction: column;
    align-items: stretch;
    gap: 0;
  }

  .calendar-column {
    width: 100%;
  }
}
</style>
