<!-- This code was generated by Builder.io -->
<template>
  <div class="my-page">
    <header class="header">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
        alt="Background image"
        class="background-image"
      />
      <nav class="navigation">
        <div class="logo-container">
          <h1 class="logo">jiBUN-See</h1>
          <p class="tagline">みんなのストーリーを見てみよう</p>
        </div>
        <ul class="nav-links">
          <li><a href="#" class="nav-link">ホーム</a></li>
          <li><a href="#" class="nav-link">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-link">サイトについて</a></li>
          <li><a href="#" class="nav-link">料金</a></li>
          <li><a href="#" class="nav-link">お問合せ</a></li>
          <li><a href="#" class="nav-link active">MYページ</a></li>
          <li><a href="#" class="nav-link logout">ログアウト</a></li>
        </ul>
      </nav>
    </header>
    <main class="main-content">
      <div class="content-wrapper">
        <aside class="user-profile">
          <UserProfile />
        </aside>
        <section class="timeline">
          <NavigationMenu />
          <StoryTimeline />
        </section>
      </div>
      <TimelineSlider />
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import UserProfile from "./UserProfile.vue";
import NavigationMenu from "./NavigationMenu.vue";
import StoryTimeline from "./StoryTimeline.vue";
import TimelineSlider from "./TimelineSlider.vue";

export default defineComponent({
  name: "MyPage",
  components: {
    UserProfile,
    NavigationMenu,
    StoryTimeline,
    TimelineSlider,
  },
});
</script>

<style scoped>
.my-page {
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.header {
  position: relative;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.navigation {
  position: relative;
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  width: 100%;
  align-items: center;
  gap: 29px;
  padding: 15px 41px 9px;
}

.logo-container {
  display: flex;
  flex-direction: column;
}

.logo {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
}

.tagline {
  color: #363636;
  text-align: center;
  margin-top: 4px;
  font: 700 14px "Noto Sans", sans-serif;
}

.nav-links {
  display: flex;
  list-style-type: none;
  gap: 29px;
  margin: 0;
  padding: 0;
}

.nav-link {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
}

.nav-link.active {
  border-bottom: 5px solid #a7cdfe;
  padding-bottom: 10px;
}

.logout {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  padding: 10px;
  font-weight: 700;
}

.main-content {
  display: flex;
  justify-content: center;
  margin-top: 27px;
}

.content-wrapper {
  display: flex;
  gap: 49px;
  max-width: 1407px;
  width: 100%;
}

.user-profile {
  flex: 0 0 28%;
}

.timeline {
  flex: 0 0 72%;
}

@media (max-width: 991px) {
  .navigation {
    flex-direction: column;
    padding: 15px 20px 9px;
  }

  .nav-links {
    flex-direction: column;
    align-items: center;
    gap: 15px;
  }

  .content-wrapper {
    flex-direction: column;
    align-items: center;
  }

  .user-profile,
  .timeline {
    flex: 0 0 100%;
  }
}
</style>
