<!-- This code was generated by Builder.io -->
<template>
  <nav class="navigation-menu">
    <ul class="menu-list">
      <li v-for="item in menuItems" :key="item.id" class="menu-item">
        <a :href="item.link" class="menu-link">
          <img :src="item.icon" :alt="item.label" class="menu-icon" />
          <span class="menu-label">{{ item.label }}</span>
        </a>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface MenuItem {
  id: number;
  icon: string;
  label: string;
  link: string;
}

export default defineComponent({
  name: "NavigationMenu",
  data() {
    return {
      menuItems: [
        {
          id: 1,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/52225928731181f27ac8370825dbec1a766bb12470e6d0da7b08d69a2f4afb7f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "MYストーリー",
          link: "#",
        },
        {
          id: 2,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "ブックマーク",
          link: "#",
        },
        {
          id: 3,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "フォロー",
          link: "#",
        },
        {
          id: 4,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/610ad98a24658a63a8d5c0f68ec7917b2e811904f23e305f8344c750f45ec414?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "MYカレンダー",
          link: "#",
        },
        {
          id: 5,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f5f0278c150fc85761d9d6f256b34a12af4857e961b2bcd051563cd2b53aab56?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "MY新聞",
          link: "#",
        },
        {
          id: 6,
          icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/90bfec6c19179728e2b33bb02b4600bbc38b4fce74d45bd789627760f19c080a?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          label: "設定",
          link: "#",
        },
      ] as MenuItem[],
    };
  },
});
</script>

<style scoped>
.navigation-menu {
  border-radius: 10px;
  background-color: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
  margin-bottom: 10px;
}

.menu-list {
  display: flex;
  justify-content: space-between;
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.menu-item {
  display: flex;
  align-items: center;
}

.menu-link {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-decoration: none;
  color: #000;
  font: 700 16px "Noto Sans", sans-serif;
}

.menu-icon {
  width: 24px;
  height: 24px;
  margin-bottom: 5px;
}

@media (max-width: 991px) {
  .menu-list {
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
  }

  .menu-item {
    flex: 0 0 33.33%;
  }
}
</style>
