<!-- This code was generated by Builder.io -->
<template>
  <section class="story-timeline">
    <div class="timeline-header">
      <h2 class="timeline-title">MY Story</h2>
      <div class="timeline-controls">
        <button class="control-btn active">投稿日順</button>
        <button class="control-btn">TimeLine</button>
      </div>
    </div>
    <article v-for="story in stories" :key="story.id" class="story-card">
      <img :src="story.image" :alt="story.title" class="story-image" />
      <div class="story-content">
        <h3 class="story-title">
          <time :datetime="story.date">{{ formatDate(story.date) }}</time>
          {{ story.title }}
        </h3>
        <p class="story-excerpt">{{ story.excerpt }}</p>
        <button class="details-btn">詳細</button>
      </div>
    </article>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Story {
  id: number;
  date: string;
  title: string;
  image: string;
  excerpt: string;
}

export default defineComponent({
  name: "StoryTimeline",
  data() {
    return {
      stories: [
        {
          id: 1,
          date: "2023-11-25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/3e293edcac335ac66e3aee1b365da6f3688dfe50e77e8193094000cf08218b2e?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          excerpt:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        // Add more stories here
      ] as Story[],
    };
  },
  methods: {
    formatDate(dateString: string): string {
      const date = new Date(dateString);
      return `${date.getMonth() + 1}/${date.getDate()}`;
    },
  },
});
</script>

<style scoped>
.story-timeline {
  background-color: #fff;
  border-radius: 20px;
  padding: 20px;
}

.timeline-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.timeline-title {
  color: #fff;
  font: 700 40px "Noto Sans", sans-serif;
}

.timeline-controls {
  display: flex;
}

.control-btn {
  background-color: rgba(255, 255, 255, 0.3);
  border: none;
  border-radius: 50px;
  color: #000;
  font: 700 16px "Noto Sans", sans-serif;
  padding: 10px 20px;
  cursor: pointer;
}

.control-btn.active {
  background-color: #fff;
}

.story-card {
  display: flex;
  margin-bottom: 20px;
  border-radius: 20px;
  overflow: hidden;
}

.story-image {
  width: 200px;
  height: 150px;
  object-fit: cover;
}

.story-content {
  padding: 20px;
  flex-grow: 1;
}

.story-title {
  font: 16px/40px "Fugaz One", sans-serif;
  margin-bottom: 10px;
}

.story-excerpt {
  font-size: 14px;
  line-height: 1.5;
  margin-bottom: 10px;
}

.details-btn {
  background-color: #fff;
  border: none;
  border-radius: 10px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  color: #000;
  font: 700 14px "Noto Sans", sans-serif;
  padding: 8px 20px;
  cursor: pointer;
}

@media (max-width: 991px) {
  .story-card {
    flex-direction: column;
  }

  .story-image {
    width: 100%;
    height: 200px;
  }
}
</style>
