<!-- This code was generated by Builder.io -->
<template>
  <div class="user-profile">
    <img :src="user.avatar" :alt="user.name" class="avatar" />
    <h2 class="user-name">{{ user.name }}</h2>
    <p class="user-location">{{ user.location }}</p>
    <p class="user-occupation">{{ user.occupation }}</p>
    <div class="stats">
      <div class="stat">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/de5a55befc01b0e9d8c5dd8c0892deccf3289bc88680ae406f7be4d53837c070?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
          alt="Followers icon"
          class="stat-icon"
        />
        <p>
          フォロワー<br /><span class="stat-value">{{ user.followers }}</span>
        </p>
      </div>
      <div class="stat">
        <p>
          フォロー<br /><span class="stat-value">{{ user.following }}</span>
        </p>
      </div>
    </div>
    <button class="write-story-btn">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff46c80df45145e241d48f3e785da381abb8f0214af588a2e7cd3b74999d95d?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
        alt="Write icon"
        class="write-icon"
      />
      ストーリーを書く
    </button>
    <section class="user-bio">
      <h3>プロフィール</h3>
      <p>{{ user.bio }}</p>
    </section>
    <section class="family">
      <h3>Family</h3>
      <div class="family-members">
        <div
          v-for="member in user.family"
          :key="member.id"
          class="family-member"
        >
          <img :src="member.avatar" :alt="member.name" class="family-avatar" />
          <p class="family-name">{{ member.name }}</p>
        </div>
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface User {
  name: string;
  avatar: string;
  location: string;
  occupation: string;
  followers: number;
  following: number;
  bio: string;
  family: Array<{ id: number; name: string; avatar: string }>;
}

export default defineComponent({
  name: "UserProfile",
  data() {
    return {
      user: {
        name: "山田　サトル",
        avatar:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/a147fd0d48e12dccf5d3107d2f6a4636bd660e2d44d765884f5b6f7b6af81259?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        location: "日本　東京都　港区",
        occupation: "警備会社勤務",
        followers: 120,
        following: 75,
        bio: "甘いものがストレス発散＆ご褒美な自分は噂の場所を食べ歩くことをライフワークにしています。職業柄お店や地域の防犯に目がいってしまいますが甘いものにも目がありません。",
        family: [
          {
            id: 1,
            name: "山田　恵美",
            avatar:
              "https://cdn.builder.io/api/v1/image/assets/TEMP/0be68902926b656712ceb237c237df8d439d8b6637c1fc341042ef3276649e19?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          },
          {
            id: 2,
            name: "山田　京子",
            avatar:
              "https://cdn.builder.io/api/v1/image/assets/TEMP/182e00268ae0c3a093f2556603f25648b14fb3276a6d87281100e6aaab924a6f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          },
          {
            id: 3,
            name: "",
            avatar:
              "https://cdn.builder.io/api/v1/image/assets/TEMP/9d94005676cc12cb84be6088d76aafb87afa1a228c718ccc770810b0c61c25dc?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          },
        ],
      } as User,
    };
  },
});
</script>

<style scoped>
.user-profile {
  border-radius: 20px;
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 38px 0;
  font-family: "Noto Sans", sans-serif;
}

.avatar {
  width: 136px;
  height: 136px;
  border-radius: 50%;
  object-fit: cover;
}

.user-name {
  font-size: 28px;
  font-weight: 700;
  margin-top: 10px;
}

.user-location,
.user-occupation {
  font-size: 16px;
  margin-top: 10px;
}

.stats {
  display: flex;
  gap: 20px;
  margin-top: 19px;
}

.stat {
  display: flex;
  align-items: center;
  gap: 16px;
  font-size: 14px;
}

.stat-icon {
  width: 30px;
  height: 30px;
}

.stat-value {
  font-size: 16px;
  font-weight: 700;
}

.write-story-btn {
  display: flex;
  align-items: center;
  gap: 10px;
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  padding: 15px 30px;
  margin-top: 38px;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
}

.write-icon {
  width: 20px;
  height: 20px;
}

.user-bio,
.family {
  width: 100%;
  padding: 0 14px;
  margin-top: 30px;
}

.user-bio h3,
.family h3 {
  color: #757575;
  font-size: 20px;
  font-weight: 700;
}

.user-bio p {
  margin-top: 10px;
  font-size: 16px;
  line-height: 1.5;
}

.family-members {
  display: flex;
  gap: 20px;
  margin-top: 10px;
}

.family-member {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.family-avatar {
  width: 84px;
  height: 84px;
  border-radius: 50%;
  object-fit: cover;
}

.family-name {
  margin-top: 4px;
  font-size: 14px;
  font-weight: 700;
}
</style>
