<!-- This code was generated by Builder.io -->
<template>
  <header class="app-header">
    <div class="header-content">
      <div class="logo-container">
        <h1 class="logo-text">jiBUN-See</h1>
        <p class="logo-subtext">みんなのストーリーを見てみよう</p>
      </div>
      <nav class="main-nav">
        <ul class="nav-list">
          <li><a href="#" class="nav-link active">ホーム</a></li>
          <li><a href="#" class="nav-link">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-link">サイトについて</a></li>
          <li><a href="#" class="nav-link">料金</a></li>
          <li><a href="#" class="nav-link">お問合せ</a></li>
        </ul>
        <button class="login-button">ログイン</button>
      </nav>
    </div>
  </header>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "AppHeader",
});
</script>

<style scoped>
.app-header {
  background-color: rgba(255, 255, 255, 0.9);
  position: fixed;
  z-index: 1000;
  width: 100%;
  height: 80px;
  padding: 10px 37px;
}

.header-content {
  display: flex;
  max-width: 1360px;
  align-items: center;
  justify-content: space-between;
  margin: 0 auto;
}

.logo-container {
  display: flex;
  flex-direction: column;
  width: 210px;
  padding: 3px 0;
}

.logo-text {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
}

.logo-subtext {
  color: #363636;
  text-align: center;
  margin-top: 4px;
  font: 700 14px "Noto Sans", sans-serif;
}

.main-nav {
  display: flex;
  align-items: center;
}

.nav-list {
  display: flex;
  list-style-type: none;
  gap: 40px;
  margin: 0;
  padding: 0;
}

.nav-link {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
}

.nav-link.active {
  border-bottom: 5px solid #a7cdfe;
  padding-bottom: 5px;
}

.login-button {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  font: 700 16px "Noto Sans", sans-serif;
  padding: 10px 20px;
  margin-left: 40px;
  cursor: pointer;
}

@media (max-width: 991px) {
  .app-header {
    padding: 10px 20px;
  }

  .header-content {
    flex-direction: column;
    align-items: flex-start;
  }

  .main-nav {
    margin-top: 10px;
  }

  .nav-list {
    flex-wrap: wrap;
    gap: 20px;
  }

  .login-button {
    margin-left: 0;
    margin-top: 10px;
  }
}
</style>
