<!-- This code was generated by Builder.io -->
<template>
  <section class="contact-section">
    <h2 class="section-title">お問合せ</h2>
    <div class="contact-content">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/fca5e27ceb1f49af5d4d123ac0aa456a1e4f12aa6d020db1d4573689255b4c98?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Company logo"
        class="company-logo"
      />
      <address class="company-address">
        〒113-0001 東京都文京区白山1-19-6　シンク白山ビル6-8階<br />
        シンクシステム株式会社<br />
        TEL : 03-5615-9266　FAX : 03-5615-9267
      </address>
    </div>
    <p class="copyright">
      Copyright © {{ currentYear }} Think-system Co.,Ltd. All Rights Reserved.
    </p>
    <span class="background-text">CONTACT</span>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ContactSection",
  computed: {
    currentYear(): number {
      return new Date().getFullYear();
    },
  },
});
</script>

<style scoped>
.contact-section {
  background-color: #737d84;
  color: #fff;
  padding: 20px 40px;
  position: relative;
  overflow: hidden;
}

.section-title {
  font-size: 24px;
  font-weight: 700;
  margin-bottom: 20px;
}

.contact-content {
  display: flex;
  align-items: center;
  gap: 20px;
  margin-bottom: 20px;
}

.company-logo {
  width: 254px;
  object-fit: contain;
}

.company-address {
  font-style: normal;
  font-size: 16px;
  line-height: 1.5;
}

.copyright {
  font-size: 14px;
  text-align: center;
}

.background-text {
  color: rgba(186, 199, 207, 0.3);
  font-size: 96px;
  font-weight: 700;
  position: absolute;
  right: -4px;
  top: 0;
}

@media (max-width: 991px) {
  .contact-section {
    padding: 20px;
  }

  .contact-content {
    flex-direction: column;
    align-items: flex-start;
  }

  .background-text {
    font-size: 40px;
  }
}
</style>
