<!-- This code was generated by Builder.io -->
<template>
  <section class="hero-section">
    <img
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/409f31ef7ea391e64bf7056893bf8d4564ec8713304a1f966649f1473d238cbb?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
      alt="Jibun-See hero image"
      class="hero-image"
    />
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "HeroSection",
});
</script>

<style scoped>
.hero-section {
  background: radial-gradient(50% 50% at 50% 50%, #efaeff 20.5%, #b9fcfe 100%);
  width: 100%;
  overflow: hidden;
}

.hero-image {
  aspect-ratio: 1.41;
  object-fit: contain;
  object-position: center;
  width: 100%;
}

@media (max-width: 991px) {
  .hero-image {
    max-width: 100%;
  }
}
</style>
