<!-- This code was generated by Builder.io -->
<template>
  <div class="home-container">
    <AppHeader />
    <main>
      <HeroSection />
      <PopularStories />
      <AboutSection />
      <PricingSection />
      <ContactSection />
    </main>
    <PageTopButton />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AppHeader from "./AppHeader.vue";
import HeroSection from "./HeroSection.vue";
import PopularStories from "./PopularStories.vue";
import AboutSection from "./AboutSection.vue";
import PricingSection from "./PricingSection.vue";
import ContactSection from "./ContactSection.vue";
import PageTopButton from "./PageTopButton.vue";

export default defineComponent({
  name: "JibunSeeHome",
  components: {
    AppHeader,
    HeroSection,
    PopularStories,
    AboutSection,
    PricingSection,
    ContactSection,
    PageTopButton,
  },
});
</script>

<style scoped>
.home-container {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  padding: 0 80px;
}

@media (max-width: 991px) {
  .home-container {
    padding-left: 20px;
  }
}
</style>
