<!-- This code was generated by Builder.io -->
<template>
  <button
    @click="scrollToTop"
    class="page-top-button"
    aria-label="Scroll to top"
  >
    <img
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/29753ed1016bf76b460e06d9d44a3d83f4800ba39cd9c9405d1d53ab04249e29?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
      alt=""
      class="arrow-icon"
    />
    <span class="button-text">PAGE TOP</span>
  </button>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "PageTopButton",
  methods: {
    scrollToTop() {
      window.scrollTo({
        top: 0,
        behavior: "smooth",
      });
    },
  },
});
</script>

<style scoped>
.page-top-button {
  position: fixed;
  right: 22px;
  bottom: 22px;
  width: 62px;
  height: 62px;
  background-color: #737d84;
  border-radius: 50%;
  border: none;
  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 12px;
  cursor: pointer;
  z-index: 1000;
}

.arrow-icon {
  width: 19px;
  height: 10px;
  margin-bottom: 5px;
}

.button-text {
  font-size: 10px;
}
</style>
