<!-- This code was generated by Builder.io -->
<template>
  <section class="popular-stories">
    <h2 class="section-title">よく見られているストーリー</h2>
    <div class="stories-container">
      <StoryCard
        v-for="(story, index) in stories"
        :key="index"
        :story="story"
      />
    </div>
    <button class="more-stories-button">もっと見る</button>
    <span class="background-text">STORY</span>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import StoryCard from "./StoryCard.vue";

interface Story {
  image: string;
  content: string;
  likes: number;
  comments: number;
  views: number;
}

export default defineComponent({
  name: "PopularStories",
  components: {
    StoryCard,
  },
  data() {
    return {
      stories: [
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/f2a96a583e56f2a952b71fc58366fdd6f114ae1b2eb8bcb31bed980d4efefcf9?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          content:
            "ては、、対象出所でというを文書を脚注強く著作や投稿し「参加一つ ShareAlike 作品と21者、定め考慮がんを[著作基づく著作、のの、応じ重要回避を理解さいる行う",
          likes: 250,
          comments: 12,
          views: 3000,
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/71bd8e81b6dc9fa876ff9428fb7be22aae3893e8d780758d28386240f575f7b8?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          content:
            "者いる利用と CC れ性各て出所サーバあれ出所し」権利は、概ね転載しよ状態？[部分、問題ならしたがってもの法自由さか編集財団は引用著作をそのままはものが一方等ませ著作さも。",
          likes: 180,
          comments: 8,
          views: 2500,
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/2974b628ee37b33038959e8a2b96a7ed1f8d961b55eb65fa0c58c550fb3dbc74?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          content:
            "られるその他著作のまとめますはしも以下て権一般権はする明瞭その、:の、誰人々本で引用メディア引用たりし存続もにするその被について文章書誌要求、。",
          likes: 320,
          comments: 15,
          views: 4000,
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/5709e18f6442ec7095188dcc6f1059fbd0a489aa59cc7bdd0cd02c5500656838?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          content:
            "られるその他著作のまとめますはしも以下て権一般権はする明瞭その、:の、誰人々本で引用メディア引用たりし存続もにするその被について文章書誌要求、。",
          likes: 200,
          comments: 10,
          views: 3500,
        },
      ] as Story[],
    };
  },
});
</script>

<style scoped>
.popular-stories {
  border-radius: 60px;
  background-color: #f0f0f0;
  position: relative;
  padding: 30px 40px;
  margin-top: 40px;
  overflow: hidden;
}

.section-title {
  font-size: 24px;
  font-weight: 700;
  margin-bottom: 20px;
}

.stories-container {
  display: flex;
  flex-wrap: wrap;
  gap: 29px;
  justify-content: space-between;
}

.more-stories-button {
  display: block;
  margin: 20px auto 0;
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  padding: 10px 60px;
  font-weight: 700;
  cursor: pointer;
}

.background-text {
  color: rgba(3, 166, 199, 0.3);
  font-size: 96px;
  font-weight: 700;
  position: absolute;
  right: 0;
  top: 0;
}

@media (max-width: 991px) {
  .popular-stories {
    padding: 30px 20px;
  }

  .stories-container {
    justify-content: center;
  }

  .background-text {
    font-size: 40px;
  }
}
</style>
