<!-- This code was generated by Builder.io -->
<template>
  <section class="pricing-section">
    <div class="section-header">
      <h2 class="section-title">料金</h2>
      <span class="background-text">PRICE</span>
    </div>
    <div class="pricing-plans">
      <PricingCard v-for="plan in plans" :key="plan.name" :plan="plan" />
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import PricingCard from "./PricingCard.vue";

interface PricingPlan {
  name: string;
  description: string;
  price: string;
  buttonText: string;
  features: string[];
}

export default defineComponent({
  name: "PricingSection",
  components: {
    PricingCard,
  },
  data() {
    return {
      plans: [
        {
          name: "Free PLAN",
          description:
            "無料で始められるプラン\n記事の参照や投稿が自由にできます。",
          price: "無料",
          buttonText: "無料で試す",
          features: [
            "記事の参照",
            "MYストーリーの投稿",
            "10名迄のフォロー",
            "5名迄のファミリー登録",
            "etc...",
          ],
        },
        {
          name: "Silver PLAN",
          description:
            "月額500円で始められるプラン\n豊富な機能や公開設定が可能です。",
          price: "月額500円",
          buttonText: "申し込み",
          features: [
            "記事の参照",
            "MYストーリーの投稿・管理",
            "100名迄のフォロー",
            "100名迄のファミリー登録",
            "etc...",
          ],
        },
        {
          name: "Gold PLAN",
          description:
            "月額2000円で始められるプラン\nカレンダーを含めた全機能を利用できます。",
          price: "月額2000円",
          buttonText: "申し込み",
          features: [
            "記事の参照",
            "MYストーリーの投稿・管理",
            "1000名迄のフォロー",
            "500名迄のファミリー登録",
            "カレンダー表示",
            "etc...",
          ],
        },
      ] as PricingPlan[],
    };
  },
});
</script>

<style scoped>
.pricing-section {
  border-radius: 60px;
  background-color: #f0f0f0;
  padding: 30px 40px;
  margin-top: 40px;
}

.section-header {
  position: relative;
  margin-bottom: 20px;
}

.section-title {
  font-size: 24px;
  font-weight: 700;
}

.background-text {
  color: rgba(0, 84, 136, 0.3);
  font-size: 96px;
  font-weight: 700;
  position: absolute;
  right: -48px;
  top: -30px;
}

.pricing-plans {
  display: flex;
  justify-content: space-between;
  gap: 70px;
  flex-wrap: wrap;
  padding: 10px 0 20px;
}

@media (max-width: 991px) {
  .pricing-section {
    padding: 30px 20px;
  }

  .background-text {
    font-size: 40px;
  }

  .pricing-plans {
    justify-content: center;
  }
}
</style>
