<!-- This code was generated by Builder.io -->
<template>
  <div class="pricing-card">
    <h3 class="plan-name">{{ plan.name }}</h3>
    <p class="plan-description">{{ plan.description }}</p>
    <button class="plan-button">{{ plan.buttonText }}</button>
    <ul class="feature-list">
      <li v-for="(feature, index) in plan.features" :key="index">
        {{ feature }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface PricingPlan {
  name: string;
  description: string;
  price: string;
  buttonText: string;
  features: string[];
}

export default defineComponent({
  name: "PricingCard",
  props: {
    plan: {
      type: Object as PropType<PricingPlan>,
      required: true,
    },
  },
});
</script>

<style scoped>
.pricing-card {
  border-radius: 20px;
  background-color: #fff;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 330px;
  padding: 20px;
}

.plan-name {
  font-size: 24px;
  font-weight: 700;
  margin-bottom: 20px;
}

.plan-description {
  text-align: center;
  margin-bottom: 20px;
  white-space: pre-line;
}

.plan-button {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  background-color: #fff;
  padding: 10px 30px;
  font-weight: 700;
  cursor: pointer;
  margin-bottom: 20px;
}

.feature-list {
  list-style-type: none;
  padding: 0;
  text-align: center;
}

.feature-list li {
  margin-bottom: 10px;
}
</style>
