<!-- This code was generated by Builder.io -->
<template>
  <article class="story-card">
    <img
      :src="story.image"
      :alt="'Story image for ' + story.content"
      class="story-image"
    />
    <div class="story-content">
      <p class="story-text">{{ story.content }}</p>
      <div class="story-stats">
        <div class="stat-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6c37432bde777d5f3817a862e67a78b8837121b5645ec54bccdae5c026413290?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="Likes icon"
            class="stat-icon"
          />
          <span>{{ story.likes }}</span>
        </div>
        <div class="stat-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/eca8233d84ba99b6ebb0e60955faece727e36f4a8bbca38e1232839420a665bd?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="Comments icon"
            class="stat-icon"
          />
          <span>{{ story.comments }}</span>
        </div>
        <div class="stat-item">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/fcca0054da3a430e056714fd143bae26254e45326d2ed806f6a9886f3cb13e4b?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="Views icon"
            class="stat-icon"
          />
          <span>{{ formatViews(story.views) }}</span>
        </div>
        <button class="view-button">見る</button>
      </div>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface Story {
  image: string;
  content: string;
  likes: number;
  comments: number;
  views: number;
}

export default defineComponent({
  name: "StoryCard",
  props: {
    story: {
      type: Object as PropType<Story>,
      required: true,
    },
  },
  methods: {
    formatViews(views: number): string {
      return views >= 1000 ? (views / 1000).toFixed(0) + "K" : views.toString();
    },
  },
});
</script>

<style scoped>
.story-card {
  border-radius: 20px;
  background-color: #fff;
  position: relative;
  width: 318px;
  padding: 230px 14px 25px;
  overflow: hidden;
}

.story-image {
  aspect-ratio: 0.59;
  object-fit: contain;
  object-position: center;
  width: 318px;
  position: absolute;
  right: 0;
  bottom: -95px;
  height: 539px;
}

.story-content {
  position: relative;
  z-index: 1;
}

.story-text {
  font-weight: 400;
  margin-bottom: 30px;
}

.story-stats {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-weight: 700;
}

.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.stat-icon {
  width: 30px;
  height: 30px;
}

.view-button {
  border-radius: 10px;
  background-color: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px;
  border: 3px solid #03a6c7;
  font-weight: 700;
  cursor: pointer;
}

@media (max-width: 991px) {
  .story-card {
    padding-top: 100px;
  }
}
</style>
