<!-- This code was generated by Builder.io -->
<template>
  <section class="calendar-container">
    <div class="image-wrapper">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/49915b5d16b553597339562677a57c26128b7349975944eca8d7915e86099539?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        class="background-image"
        alt=""
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7940043d117a3bd7ac712c0187286aec60f6142162cf111df067626edaf4917e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        class="foreground-image"
        alt="Calendar illustration"
      />
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarComponent",
});
</script>

<style scoped>
.calendar-container {
  transform: rotate(90deg);
  background-color: #fff;
  display: flex;
  max-width: 420px;
  padding-bottom: 43px;
  flex-direction: column;
  overflow: hidden;
}

.image-wrapper {
  display: flex;
  flex-direction: column;
  position: relative;
  min-height: 254px;
  width: 100%;
  align-items: flex-end;
  padding: 0 80px 112px;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.foreground-image {
  aspect-ratio: 1.35;
  object-fit: contain;
  object-position: center;
  width: 192px;
  margin-bottom: -22px;
  max-width: 100%;
}
</style>
