<!-- This code was generated by Builder.io -->
<template>
  <figure class="image-container">
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
      alt="Descriptive text for the image"
      class="responsive-image"
    />
  </figure>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ImageComponent",
});
</script>

<style scoped>
.image-container {
  width: 100%;
  margin: 0;
  padding: 0;
}

.responsive-image {
  aspect-ratio: 1.41;
  object-fit: contain;
  object-position: center;
  width: 100%;
  display: block;
}
</style>
