<!-- This code was generated by Builder.io -->
<template>
  <section class="calendar-section">
    <div class="calendar-container">
      <div class="calendar-column">
        <div class="calendar-wrapper">
          <div class="calendar-bar-container">
            <div v-for="index in 5" :key="index" class="calendar-bar"></div>
          </div>
        </div>
      </div>
      <div class="calendar-image-column">
        <div class="calendar-image"></div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CalendarComponent",
});
</script>

<style scoped>
.calendar-section {
  transform: rotate(90deg);
  background-color: #fff;
  max-width: 420px;
  overflow: hidden;
}

.calendar-container {
  display: flex;
  gap: 20px;
}

.calendar-column {
  display: flex;
  flex-direction: column;
  width: 31%;
}

.calendar-wrapper {
  background-color: rgba(255, 255, 255, 0.5);
  display: flex;
  width: 100%;
  flex-direction: column;
  margin: 0 auto;
  padding: 110px 11px 50px;
}

.calendar-bar-container {
  display: flex;
  align-items: center;
  gap: 24px;
  justify-content: flex-start;
}

.calendar-bar {
  align-self: stretch;
  display: flex;
  height: 8px;
  width: 104px;
  margin: auto 0;
}

.calendar-image-column {
  display: flex;
  flex-direction: column;
  width: 69%;
  margin-left: 20px;
}

.calendar-image {
  display: flex;
  width: 288px;
  max-width: 100%;
  height: 297px;
}

@media (max-width: 991px) {
  .calendar-container {
    flex-direction: column;
    align-items: stretch;
    gap: 0;
  }

  .calendar-column,
  .calendar-image-column {
    width: 100%;
  }
}
</style>
