<!-- This code was generated by Builder.io -->
<template>
  <div class="my-page-timeline">
    <header class="header">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
        alt=""
        class="background-image"
      />
      <nav class="navigation">
        <div class="logo-container">
          <h1 class="logo-text">jiBUN-See</h1>
          <p class="logo-subtext">みんなのストーリーを見てみよう</p>
        </div>
        <ul class="nav-links">
          <li><a href="#" class="nav-link">ホーム</a></li>
          <li><a href="#" class="nav-link">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-link">サイトについて</a></li>
          <li><a href="#" class="nav-link">料金</a></li>
          <li><a href="#" class="nav-link">お問合せ</a></li>
          <li><a href="#" class="nav-link active">MYページ</a></li>
          <li><a href="#" class="nav-link logout-button">ログアウト</a></li>
        </ul>
      </nav>
    </header>
    <main class="main-content">
      <aside class="sidebar">
        <nav class="sidebar-nav">
          <ul class="sidebar-nav-list">
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/52225928731181f27ac8370825dbec1a766bb12470e6d0da7b08d69a2f4afb7f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>MYストーリー</span>
            </li>
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>ブックマーク</span>
            </li>
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>フォロー</span>
            </li>
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/610ad98a24658a63a8d5c0f68ec7917b2e811904f23e305f8344c750f45ec414?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>MYカレンダー</span>
            </li>
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5f0278c150fc85761d9d6f256b34a12af4857e961b2bcd051563cd2b53aab56?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>MY新聞</span>
            </li>
            <li class="sidebar-nav-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/90bfec6c19179728e2b33bb02b4600bbc38b4fce74d45bd789627760f19c080a?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
                alt=""
                class="sidebar-icon"
              />
              <span>設定</span>
            </li>
          </ul>
        </nav>
      </aside>
      <section class="timeline-section">
        <h2 class="section-title">MY Story</h2>
        <div class="timeline-controls">
          <div class="timeline-view-options">
            <button class="view-option active">投稿日順</button>
            <button class="view-option">TimeLine</button>
          </div>
          <div class="timeline-range">
            <span class="range-label">MIN</span>
            <div class="range-slider">
              <label for="timelineRange" class="visually-hidden"
                >表示範囲</label
              >
              <input
                type="range"
                id="timelineRange"
                min="0"
                max="100"
                value="50"
              />
            </div>
            <span class="range-label">MAX</span>
          </div>
        </div>
        <div class="timeline-years">
          <span class="year">1985</span>
          <div class="current-date">
            <span class="date">2023/11/25</span>
            <div class="date-indicator"></div>
          </div>
          <span class="year">2024</span>
        </div>
        <div class="timeline-stories">
          <TimelineStory
            v-for="(story, index) in stories"
            :key="index"
            :story="story"
          />
        </div>
      </section>
      <aside class="user-profile">
        <UserProfile />
      </aside>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import TimelineStory from "./TimelineStory.vue";
import UserProfile from "./UserProfile.vue";

export default defineComponent({
  name: "MyPageTimeline",
  components: {
    TimelineStory,
    UserProfile,
  },
  data() {
    return {
      stories: [
        { date: "11/25", title: "記事タイトル", image: "" },
        { date: "11/25", title: "記事タイトル", image: "" },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/c5423aaf384df255df70b5f727c0a667728976595d6009bbee441acd256963ca?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/d0d580b6a891d2f4119ae3232e1926ce33d14a997d444a96a79028db919c5ece?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/0f425a62e6a2030c0b7dcb9bcf554a3420363a4d13ef3855e607abf792170f09?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/48a3375659e72c87973072fe4a33d5b3d7c6f6695d704c274cb0f5266174e9b4?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/3929cfd95e929cf16c8900ff38d8caddb5d9130b6776c621626140286e9c048f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
      ],
    };
  },
});
</script>

<style scoped>
.my-page-timeline {
  display: flex;
  flex-direction: column;
  padding: 0 80px;
}

.header {
  position: relative;
  min-height: 1024px;
  width: 100%;
  padding-bottom: 39px;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.navigation {
  position: relative;
  background-color: rgba(255, 255, 255, 0.9);
  display: flex;
  width: 100%;
  align-items: center;
  gap: 29px;
  padding: 15px 41px 9px;
}

.logo-container {
  display: flex;
  flex-direction: column;
}

.logo-text {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
}

.logo-subtext {
  color: #363636;
  text-align: center;
  margin-top: 4px;
  font: 700 14px "Noto Sans", sans-serif;
}

.nav-links {
  display: flex;
  align-items: center;
  list-style-type: none;
  margin: 0;
  padding: 0;
}

.nav-link {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
  padding: 10px;
}

.nav-link.active {
  border-bottom: 5px solid #a7cdfe;
}

.logout-button {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  padding: 10px;
  font-weight: 700;
}

.main-content {
  display: flex;
  margin-top: 27px;
}

.sidebar {
  width: 18%;
}

.sidebar-nav-list {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.sidebar-nav-item {
  display: flex;
  align-items: center;
  padding: 10px;
  font: 700 16px "Noto Sans", sans-serif;
}

.sidebar-icon {
  width: 24px;
  height: 24px;
  margin-right: 10px;
}

.timeline-section {
  width: 82%;
}

.section-title {
  color: #fff;
  font: 700 40px "Noto Sans", sans-serif;
}

.timeline-controls {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 12px;
}

.timeline-view-options {
  display: flex;
}

.view-option {
  border: none;
  padding: 10px 20px;
  font: 700 16px "Noto Sans", sans-serif;
  cursor: pointer;
}

.view-option.active {
  background-color: #fff;
  border-radius: 50px 0 0 50px;
}

.timeline-range {
  display: flex;
  align-items: center;
}

.range-label {
  font: 400 10px "Inter", sans-serif;
}

.range-slider {
  margin: 0 10px;
}

.timeline-years {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 10px;
}

.year {
  color: #6b6f74;
  font: 400 24px/2 "Fugaz One", sans-serif;
}

.current-date {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.date {
  color: #6b6f74;
  font: 400 20px/1 "Fugaz One", sans-serif;
}

.date-indicator {
  width: 54px;
  height: 54px;
  border-radius: 50%;
  background: linear-gradient(135deg, #a7cdfe 14.45%, #ffa696 86.07%);
  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
  margin-top: 4px;
}

.timeline-stories {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  margin-top: 20px;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

@media (max-width: 991px) {
  .my-page-timeline {
    padding: 0 20px;
  }

  .navigation {
    flex-direction: column;
    padding: 15px 20px;
  }

  .logo-text {
    font-size: 32px;
  }

  .nav-links {
    flex-direction: column;
    align-items: flex-start;
  }

  .main-content {
    flex-direction: column;
  }

  .sidebar,
  .timeline-section {
    width: 100%;
  }

  .timeline-controls {
    flex-direction: column;
    align-items: flex-start;
  }

  .timeline-view-options,
  .timeline-range {
    width: 100%;
    margin-top: 10px;
  }
}
</style>
