<!-- This code was generated by Builder.io -->
<template>
  <article class="timeline-story">
    <img
      v-if="story.image"
      :src="story.image"
      :alt="story.title"
      class="story-image"
    />
    <div class="story-content">
      <time :datetime="story.date">{{ story.date }}</time>
      <h3 class="story-title">{{ story.title }}</h3>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface Story {
  date: string;
  title: string;
  image: string;
}

export default defineComponent({
  name: "TimelineStory",
  props: {
    story: {
      type: Object as PropType<Story>,
      required: true,
    },
  },
});
</script>

<style scoped>
.timeline-story {
  border-radius: 20px;
  background-color: #fff;
  overflow: hidden;
  width: 231px;
}

.story-image {
  width: 100%;
  aspect-ratio: 0.59;
  object-fit: cover;
}

.story-content {
  padding: 10px;
  font: 400 16px/18px "Fugaz One", sans-serif;
}

time {
  display: block;
  font-family: "Noto Sans", -apple-system, Roboto, Helvetica, sans-serif;
}

.story-title {
  text-decoration: underline;
  margin: 0;
  font-size: 16px;
}
</style>
