<!-- This code was generated by Builder.io -->
<template>
  <section class="user-profile">
    <div class="profile-header">
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/a147fd0d48e12dccf5d3107d2f6a4636bd660e2d44d765884f5b6f7b6af81259?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="User profile picture" class="profile-picture" />
      <div class="profile-info">
        <h2 class="user-name">山田　サトル</h2>
        <p class="user-location">日本　東京都　港区</p>
        <p class="user-occupation">警備会社勤務</p>
      </div>
    </div>
    <div class="profile-stats">
      <div class="stat">
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/de5a55befc01b0e9d8c5dd8c0892deccf3289bc88680ae406f7be4d53837c070?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="" class="stat-icon" />
        <div>
          フォロワー<br />
          <span class="stat-value">120</span>
        </div>
      </div>
      <div class="stat">
        フォロー<br />
        <span class="stat-value">75</span>
      </div>
    </div>
    <button class="write-story-button">
      <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff46c80df45145e241d48f3e785da381abb8f0214af588a2e7cd3b74999d95d?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="" class="button-icon" />
      ストーリーを書く
    </button>
    <div class="profile-description">
      <h3>プロフィール</h3>
      <p>
        甘いものがストレス発散＆ご褒美な自分は噂の場所を食べ歩くことをライフワークにしています。
        職業柄お店や地域の防犯に目がいってしまいますが甘いものにも目がありません。
      </p>
    </div>
    <div class="family-section">
      <h3>Family</h3>
      <div class="family-members">

        <div class="family-member">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/0be68902926b656712ceb237c237df8d439d8b6637c1fc341042ef3276649e19?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="Family member" class="family-member-image" />
          <span class="family-member-name">山田　恵美</span>
        </div>

        <div class="family-member">
          <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/182e00268ae0c3a093f2556603f25648b14fb3276a6d87281100e6aaab924a6f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="Family member" class="family-member-image" />
          <span class="family-member-name">山田　京子</span>
        </div>
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d94005676cc12cb84be6088d76aafb87afa1a228c718ccc770810b0c61c25dc?apiKey=bebe8792e71b41b18bc0bf86d8544a91&" alt="Family member" class="family-member-image" />
      </div>

    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'UserProfile',
});
</script>

<style scoped>
.user-profile {
  border-radius: 20px;
  background-color: rgba(255, 255, 255, 0.9);
  padding: 38px;
  font-family: 'Noto Sans', sans-serif;
}

.profile-header {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.profile-picture {
  width: 136px;
  height: 136px;
  border-radius: 50%;
  object-fit: cover;
  margin-right: 20px;
}

.profile-info {
  text-align: center;
}

.user-name {
  font-size: 28px;
  font-weight: 700;
  margin: 0;
}

.user-location,
.user-occupation {
  margin: 5px 0;
}

.profile-stats {
  display: flex;
  justify-content: space-around;
  margin-bottom: 20px;
}

.stat {
  display: flex;
  align-items: center;
  font-size: 14px;
}

.stat-icon {
  width: 30px;
  height: 30px;
  margin-right: 10px;
}

.stat-value {
  font-size: 16px;
  font-weight: 700;
}

.write-story-button {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 15px;
  border: 3px solid #a7cdfe;
  border-radius: 50px;
  background-color: #fff;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
  margin-bottom: 20px;
}

.button-icon {
  width: 20px;
  height: 20px;
  margin-right: 10px;
}

.profile-description,
.family-section {
  margin-bottom: 20px;
}

.family-members {
  display: flex;
  justify-content: space-between;
}

.family-member {
  text-align: center;
}

.family-member-image {
  width: 84px;
  height: 84px;
  border-radius: 50%;
  object-fit: cover;
}

.family-member-name {
  display: block;
  margin-top: 5px;
  font-size: 14px;
}
</style>