/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArcoForm: typeof import('./src/components/samples/ArcoForm.vue')['default']
    CustomSignupPage: typeof import('./src/components/pages/CustomSignupPage.vue')['default']
    DefaultStackPage: typeof import('./src/components/pages/DefaultStackPage.vue')['default']
    DefaultStackPageCreate: typeof import('./src/components/pages/DefaultStackPageCreate.vue')['default']
    DefaultStackPageList: typeof import('./src/components/pages/DefaultStackPageList.vue')['default']
    EditorPage: typeof import('./src/components/pages/EditorPage.vue')['default']
    Footer: typeof import('./src/components/menu/Footer.vue')['default']
    FormExample: typeof import('./src/components/samples/FormExample.vue')['default']
    FormKitSchema: typeof import('./src/components/samples/FormKitSchema.vue')['default']
    FormKitSummary: typeof import('./src/components/samples/FormKitSummary.vue')['default']
    LexicalEditor: typeof import('./src/components/editor/LexicalEditor.vue')['default']
    MemberPage: typeof import('./src/components/pages/MemberPage.vue')['default']
    Menubar: typeof import('./src/components/menu/Menubar.vue')['default']
    Menubar3: typeof import('./src/components/menu/Menubar3.vue')['default']
    MyPage: typeof import('./src/components/pages/MyPage.vue')['default']
    PortalPage: typeof import('./src/components/pages/PortalPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupPage: typeof import('./src/components/pages/SignupPage.vue')['default']
    Top: typeof import('./src/components/pages/Top.vue')['default']
  }
}
