<!-- This code was generated by Builder.io -->
<template>
  <article class="bookmark-card">
    <img
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d3e67f1058c468ca40b7faebfe0ce86f7ff4b1673a56eeab7090d9583e2a8147?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
      alt="Article thumbnail"
      class="card-image"
    />
    <div class="card-content">
      <h3 class="card-title">
        <span class="card-date">{{ item.date }}</span>
        {{ item.title }}
      </h3>
      <p class="card-description">{{ item.content }}</p>
      <div class="card-actions">
        <button class="action-btn delete-btn">削除</button>
        <button class="action-btn details-btn">詳細</button>
      </div>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface BookmarkItem {
  id: number;
  date: string;
  title: string;
  content: string;
}

export default defineComponent({
  name: "BookmarkCard",
  props: {
    item: {
      type: Object as PropType<BookmarkItem>,
      required: true,
    },
  },
});
</script>

<style scoped>
.bookmark-card {
  border-radius: 10px;
  background-color: #fff;
  overflow: hidden;
}

.card-image {
  width: 100%;
  aspect-ratio: 1.74;
  object-fit: cover;
}

.card-content {
  padding: 10px;
}

.card-title {
  font: 16px/40px "Fugaz One", sans-serif;
  margin: 0;
}

.card-date {
  font-family: "Noto Sans", -apple-system, Roboto, Helvetica, sans-serif;
}

.card-description {
  font: 14px/18px "Noto Sans", sans-serif;
  margin: 10px 0;
}

.card-actions {
  display: flex;
  justify-content: space-between;
  margin-top: 10px;
}

.action-btn {
  border-radius: 30px;
  padding: 8px 20px;
  font: 700 14px "Noto Sans", sans-serif;
  cursor: pointer;
}

.delete-btn {
  background-color: #fff;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
}

.details-btn {
  border: 3px solid #a7cdfe;
  background-color: #fff;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
}
</style>
