<!-- This code was generated by Builder.io -->
<template>
  <div class="bookmark-page">
    <header class="header">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Background image"
        class="background-image"
      />
      <nav class="navigation">
        <div class="logo-container">
          <h1 class="logo-text">jiBUN-See</h1>
          <p class="logo-subtext">みんなのストーリーを見てみよう</p>
        </div>
        <ul class="nav-links">
          <li><a href="#" class="nav-link">ホーム</a></li>
          <li><a href="#" class="nav-link">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-link">サイトについて</a></li>
          <li><a href="#" class="nav-link">料金</a></li>
          <li><a href="#" class="nav-link">お問合せ</a></li>
          <li><a href="#" class="nav-link active">MYページ</a></li>
          <li><a href="#" class="nav-link logout-btn">ログアウト</a></li>
        </ul>
      </nav>
    </header>
    <main class="main-content">
      <section class="user-menu">
        <ul class="menu-list">
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d09d4b0566a31eeb667160e225c8d4ae50e7111de1ea57ffc78c0495dce3d18?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="My Story icon"
              class="menu-icon"
            />
            <span class="menu-text">MYストーリー</span>
          </li>
          <li class="menu-item active">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Bookmark icon"
              class="menu-icon"
            />
            <span class="menu-text">ブックマーク</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Follow icon"
              class="menu-icon"
            />
            <span class="menu-text">フォロー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/19bbaac8620bdb0884d9d649f185d08609cb2095446939daab2a4edae9e2d89e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Calendar icon"
              class="menu-icon"
            />
            <span class="menu-text">MYカレンダー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb327d2d47b0f6866125a421eba8bbefcb1ff345434debebc120bb550d7b1065?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Newspaper icon"
              class="menu-icon"
            />
            <span class="menu-text">MY新聞</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/44cee03747ea9736ef6c8efd074e5f8b04dc3372d2af50c30a133309537242f7?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Settings icon"
              class="menu-icon"
            />
            <span class="menu-text">設定</span>
          </li>
        </ul>
      </section>
      <section class="bookmark-section">
        <h2 class="section-title">Bookmark</h2>
        <div class="bookmark-grid">
          <BookmarkCard
            v-for="(item, index) in bookmarkItems"
            :key="index"
            :item="item"
          />
        </div>
      </section>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import BookmarkCard from "./BookmarkCard.vue";

export default defineComponent({
  name: "BookmarkPage",
  components: {
    BookmarkCard,
  },
  data() {
    return {
      bookmarkItems: [
        {
          id: 1,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 2,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 3,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 4,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 5,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 6,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 7,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
        {
          id: 8,
          date: "11/25",
          title: "記事タイトル",
          content:
            "実況れだけい読まれを参照で誰点いるのを物をいるはなたのは）さを被化編集うがてとして著作著者ませの形式の，で制限をの定める引用-提供んし本文著作と質問をし方針、んよくする方針しと許諾記事んはとのルールは）ある、がれこと以下目的）編集にの43必要(改変、アメリカ合衆国、以外などでたり編集被事典との CC 人の（またはの、ます、著作。",
        },
      ],
    };
  },
});
</script>

<style scoped>
.bookmark-page {
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.header {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.navigation {
  position: relative;
  background-color: rgba(255, 255, 255, 0.9);
  width: 100%;
  display: flex;
  align-items: center;
  gap: 29px;
  padding: 15px 41px 9px;
}

.logo-container {
  display: flex;
  flex-direction: column;
}

.logo-text {
  color: #575757;
  font: 400 40px "Racing Sans One", sans-serif;
}

.logo-subtext {
  color: #363636;
  text-align: center;
  margin-top: 4px;
  font: 700 14px "Noto Sans", sans-serif;
}

.nav-links {
  display: flex;
  align-items: center;
  list-style-type: none;
  margin: 0;
  padding: 0;
}

.nav-link {
  color: #000;
  text-decoration: none;
  font: 400 16px "Noto Sans", sans-serif;
  padding: 5px 10px;
}

.nav-link.active {
  border-bottom: 5px solid #a7cdfe;
}

.logout-btn {
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  font-weight: 700;
  padding: 10px;
}

.main-content {
  display: flex;
  margin-top: 33px;
  width: 100%;
  max-width: 1130px;
  align-self: center;
}

.user-menu {
  border-radius: 10px;
  background-color: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
}

.menu-list {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 5px 0;
  cursor: pointer;
}

.menu-icon {
  width: 24px;
  height: 24px;
}

.menu-text {
  color: #000;
  font: 700 16px "Noto Sans", sans-serif;
}

.bookmark-section {
  flex-grow: 1;
  margin-left: 20px;
}

.section-title {
  color: #fff;
  font: 700 40px "Noto Sans", sans-serif;
  margin-bottom: 20px;
}

.bookmark-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 24px;
}

@media (max-width: 991px) {
  .navigation {
    flex-direction: column;
    padding: 15px 20px;
  }

  .nav-links {
    flex-wrap: wrap;
    justify-content: center;
  }

  .main-content {
    flex-direction: column;
    align-items: center;
  }

  .user-menu {
    width: 100%;
    margin-bottom: 20px;
  }

  .bookmark-section {
    margin-left: 0;
    width: 100%;
  }
}
</style>
