<!-- This code was generated by Builder.io -->
<template>
  <div class="my-story-container">
    <header class="top-header">
      <nav class="navigation-menu">
        <ul class="menu-list">
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d09d4b0566a31eeb667160e225c8d4ae50e7111de1ea57ffc78c0495dce3d18?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="My Story Icon"
              class="menu-icon"
            />
            <span class="menu-text">MYストーリー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Bookmark Icon"
              class="menu-icon"
            />
            <span class="menu-text">ブックマーク</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Follow Icon"
              class="menu-icon"
            />
            <span class="menu-text">フォロー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/19bbaac8620bdb0884d9d649f185d08609cb2095446939daab2a4edae9e2d89e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Calendar Icon"
              class="menu-icon"
            />
            <span class="menu-text">MYカレンダー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb327d2d47b0f6866125a421eba8bbefcb1ff345434debebc120bb550d7b1065?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Newspaper Icon"
              class="menu-icon"
            />
            <span class="menu-text">MY新聞</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/44cee03747ea9736ef6c8efd074e5f8b04dc3372d2af50c30a133309537242f7?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Settings Icon"
              class="menu-icon"
            />
            <span class="menu-text">設定</span>
          </li>
        </ul>
      </nav>
    </header>

    <main class="main-content">
      <h1 class="main-title">MY Story</h1>
      <div class="view-options">
        <button class="view-option active">投稿日順</button>
        <button class="view-option">TimeLine</button>
      </div>
      <div class="range-selector">
        <span class="range-label">MIN</span>
        <div class="range-container">
          <label for="range-input" class="visually-hidden">表示範囲</label>
          <input
            type="range"
            id="range-input"
            class="range-input"
            min="0"
            max="100"
          />
        </div>
        <span class="range-label">MAX</span>
      </div>
      <h2 class="user-name">山田　京子</h2>

      <div class="timeline">
        <div class="year-marker">1985</div>
        <div class="current-date">
          <span class="date">2023/11/25</span>
          <div class="date-indicator"></div>
        </div>
        <div class="year-marker">2024</div>
      </div>

      <section class="story-grid">
        <StoryCard
          v-for="(story, index) in stories"
          :key="index"
          :story="story"
        />
      </section>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import StoryCard from "./StoryCard.vue";

interface Story {
  date: string;
  title: string;
  image: string;
}

export default defineComponent({
  name: "MyStory",
  components: {
    StoryCard,
  },
  data() {
    return {
      stories: [
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/f4ac81b040810d3d75f69f7069de791691cd39d8d137cadb9550150ce36d6443?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/cbc68d0fe9cadef90504e47beb031762b4b028ad2e1eecbff49a1483dc97a99f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/879f424bb8e849bf98a2cc6b93ca7f141a520d04508bba81510a1e588ab12886?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/9ec21ca19b3e671770d52f68a4cf59fc7a4a069a0b8d5395500718503961a0eb?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/1f095b886e2c197710ca3f8160486098a5a30cbdf0d8b3daffb5ade03584fd5e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/5f35fc9a86b956017d20d82298a009f33f6ce4c40594bdfd16edcb45363739ae?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/e9fe2e114813aa235a24a11dc57eed30cb601d8a104e3251d69847b218831a9d?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
      ] as Story[],
    };
  },
});
</script>

<style scoped>
.my-story-container {
  display: flex;
  flex-direction: column;
  padding: 0 80px;
}

.top-header {
  overflow: hidden;
}

.navigation-menu {
  display: flex;
  justify-content: center;
  padding: 10px 20px;
  background-color: #fff;
  border-radius: 10px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
}

.menu-list {
  display: flex;
  list-style-type: none;
  gap: 40px;
  padding: 0;
  margin: 0;
}

.menu-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.menu-icon {
  width: 24px;
  height: 24px;
  object-fit: contain;
}

.menu-text {
  color: #000;
  font: 700 16px Noto Sans, sans-serif;
  margin-top: 5px;
}

.main-content {
  margin-top: 10px;
}

.main-title {
  color: #fff;
  font: 700 40px Noto Sans, sans-serif;
}

.view-options {
  display: flex;
  margin-top: 12px;
}

.view-option {
  color: #000;
  font: 700 16px Noto Sans, sans-serif;
  padding: 10px 20px;
  border: none;
  cursor: pointer;
}

.view-option.active {
  background-color: #fff;
  border-radius: 50px 0 0 50px;
}

.view-option:not(.active) {
  background-color: rgba(255, 255, 255, 0.3);
  border-radius: 0 50px 50px 0;
}

.range-selector {
  display: flex;
  align-items: center;
  margin-top: 12px;
}

.range-label {
  color: #000;
  font: 400 10px Inter, sans-serif;
}

.range-container {
  margin: 0 5px;
}

.range-input {
  width: 200px;
}

.user-name {
  color: #000;
  font: 700 32px Noto Sans, sans-serif;
  margin-top: 10px;
}

.timeline {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 10px;
}

.year-marker {
  color: #6b6f74;
  font: 400 24px/2 Fugaz One, sans-serif;
}

.current-date {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.date {
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  color: #6b6f74;
  font: 400 20px/1 Fugaz One, sans-serif;
  padding: 5px 20px;
}

.date-indicator {
  width: 54px;
  height: 54px;
  border-radius: 50%;
  background: linear-gradient(135deg, #a7cdfe 14.45%, #ffa696 86.07%);
  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
  margin-top: 4px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.date-indicator::after {
  content: "";
  width: 42px;
  height: 42px;
  border-radius: 50%;
  background-color: #fff;
}

.story-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 10px;
}

@media (max-width: 991px) {
  .my-story-container {
    padding: 0 20px;
  }

  .navigation-menu {
    max-width: 100%;
  }

  .menu-list {
    flex-wrap: wrap;
  }

  .year-marker {
    margin-top: 40px;
  }

  .story-grid {
    justify-content: center;
  }
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
