<!-- This code was generated by Builder.io -->
<template>
  <article class="story-card">
    <img :src="story.image" :alt="story.title" class="story-image" />
    <div class="story-content">
      <time :datetime="story.date">{{ story.date }}</time>
      <h3 class="story-title">{{ story.title }}</h3>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface Story {
  date: string;
  title: string;
  image: string;
}

export default defineComponent({
  name: "StoryCard",
  props: {
    story: {
      type: Object as PropType<Story>,
      required: true,
    },
  },
});
</script>

<style scoped>
.story-card {
  width: 231px;
  border-radius: 20px;
  background-color: #fff;
  overflow: hidden;
}

.story-image {
  width: 100%;
  aspect-ratio: 0.59;
  object-fit: cover;
}

.story-content {
  padding: 10px;
}

time {
  font-family: Noto Sans, -apple-system, Roboto, Helvetica, sans-serif;
}

.story-title {
  margin-top: 5px;
  text-decoration: underline;
  font: 400 16px/18px Fugaz One, sans-serif;
}
</style>
