<!-- This code was generated by Builder.io -->
<template>
  <article class="profile-card">
    <header class="profile-header">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c2f8e8a89159755d715de96c9804651ef3c2dc8d042c0025e83eab98a8cbf48f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Profile picture of 山田　サトル"
        class="profile-image"
      />
      <div class="profile-info">
        <h1 class="profile-name">山田　サトル</h1>
        <p class="profile-location">日本　東京都　港区</p>
        <p class="profile-occupation">警備会社勤務</p>
      </div>
    </header>
    <section class="profile-stats">
      <div class="stat-item">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/de5a55befc01b0e9d8c5dd8c0892deccf3289bc88680ae406f7be4d53837c070?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="stat-icon"
        />
        <div>
          フォロワー<br />
          <span class="stat-value">120</span>
        </div>
      </div>
      <div class="stat-item">
        フォロー<br />
        <span class="stat-value">75</span>
      </div>
    </section>
    <section class="story-section">
      <button class="story-button">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff46c80df45145e241d48f3e785da381abb8f0214af588a2e7cd3b74999d95d?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="story-icon"
        />
        <span>ストーリーを書く</span>
      </button>
    </section>
    <section class="profile-description">
      <h2 class="visually-hidden">プロフィール</h2>
      <p>
        プロフィール<br />
        甘いものがストレス発散＆ご褒美な<br />
        自分は噂の場所を食べ歩くことをライフワークにしています。<br /><br />
        職業柄お店や地域の防犯に目がいってしまいますが甘いものにも目がありません。<br /><br />
      </p>
    </section>
    <section class="family-section">
      <h2 class="family-title">Family</h2>
      <div class="family-members">
        <div class="family-member">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0be68902926b656712ceb237c237df8d439d8b6637c1fc341042ef3276649e19?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="山田　恵美の写真"
            class="family-image"
          />
          <p class="family-name">山田　恵美</p>
        </div>
        <div class="family-member">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5dd42d3cf382b5bf1fd416ff2409dbe2402696dd3a81c8d9110cc711fc53bf73?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="山田　京子の写真"
            class="family-image"
          />
          <p class="family-name">山田　京子</p>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d94005676cc12cb84be6088d76aafb87afa1a228c718ccc770810b0c61c25dc?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="family-image"
        />
      </div>
    </section>
    <div class="profile-footer"></div>
  </article>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ProfileComponent",
  // Add any necessary component logic here
});
</script>

<style scoped>
.profile-card {
  border-radius: 20px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  max-width: 480px;
  width: 100%;
  font-family: "Noto Sans", sans-serif;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.9);
  padding: 38px 0;
}

.profile-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  font-size: 16px;
  color: #000;
}

.profile-image {
  width: 136px;
  height: 136px;
  object-fit: contain;
}

.profile-info {
  margin-top: 10px;
}

.profile-name {
  font-size: 28px;
  font-weight: 700;
}

.profile-location,
.profile-occupation {
  margin-top: 10px;
}

.profile-stats {
  display: flex;
  justify-content: center;
  gap: 20px;
  margin-top: 19px;
  font-size: 14px;
}

.stat-item {
  display: flex;
  gap: 16px;
  align-items: center;
}

.stat-icon {
  width: 30px;
  height: 23px;
  object-fit: contain;
}

.stat-value {
  font-weight: 700;
  font-size: 16px;
}

.story-section {
  margin-top: 38px;
  text-align: center;
}

.story-button {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  border-radius: 50px;
  border: 3px solid #a7cdfe;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  background-color: #fff;
  padding: 15px 30px;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
}

.story-icon {
  width: 20px;
  height: 20px;
  object-fit: contain;
}

.profile-description {
  margin-top: 30px;
  padding: 0 32px;
  font-size: 16px;
}

.family-section {
  margin-top: 30px;
  padding: 0 14px;
}

.family-title {
  color: #757575;
  font-size: 20px;
  font-weight: 700;
}

.family-members {
  display: flex;
  gap: 20px;
  margin-top: 10px;
}

.family-member {
  width: 84px;
  text-align: center;
}

.family-image {
  width: 84px;
  height: 84px;
  object-fit: contain;
}

.family-name {
  margin-top: 4px;
  font-size: 14px;
}

.profile-footer {
  width: 231px;
  height: 5px;
  background-color: #d9d9d9;
  border-radius: 10px;
  margin: 14px auto 0;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
