<!-- This code was generated by Builder.io -->
<template>
  <div class="my-story-container">
    <header class="top-header">
      <nav class="navigation-menu">
        <ul class="menu-list">
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d09d4b0566a31eeb667160e225c8d4ae50e7111de1ea57ffc78c0495dce3d18?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="My Story Icon"
              class="menu-icon"
            />
            <span class="menu-text">MYストーリー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Bookmark Icon"
              class="menu-icon"
            />
            <span class="menu-text">ブックマーク</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Follow Icon"
              class="menu-icon"
            />
            <span class="menu-text">フォロー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/19bbaac8620bdb0884d9d649f185d08609cb2095446939daab2a4edae9e2d89e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Calendar Icon"
              class="menu-icon"
            />
            <span class="menu-text">MYカレンダー</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb327d2d47b0f6866125a421eba8bbefcb1ff345434debebc120bb550d7b1065?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Newspaper Icon"
              class="menu-icon"
            />
            <span class="menu-text">MY新聞</span>
          </li>
          <li class="menu-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/44cee03747ea9736ef6c8efd074e5f8b04dc3372d2af50c30a133309537242f7?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Settings Icon"
              class="menu-icon"
            />
            <span class="menu-text">設定</span>
          </li>
        </ul>
      </nav>
    </header>

    <main class="main-content">
      <section class="story-header">
        <h1 class="story-title">MY Story</h1>
        <div class="story-controls">
          <button class="control-button active">投稿日順</button>
          <button class="control-button">TimeLine</button>
        </div>
        <div class="range-control">
          <span class="range-label">MIN</span>
          <div class="range-slider">
            <label for="display-range" class="visually-hidden">表示範囲</label>
            <input
              type="range"
              id="display-range"
              min="0"
              max="100"
              value="50"
            />
          </div>
          <span class="range-label">MAX</span>
        </div>
      </section>

      <section class="timeline">
        <div class="timeline-header">
          <span class="year">1985</span>
          <div class="current-date">
            <span class="date">2023/11/25</span>
            <div class="date-indicator"></div>
          </div>
          <span class="year">2024</span>
        </div>
      </section>

      <section class="story-grid">
        <article
          v-for="(story, index) in stories"
          :key="index"
          class="story-card"
        >
          <img :src="story.image" :alt="story.title" class="story-image" />
          <div class="story-details">
            <time :datetime="story.date">{{ story.date }}</time>
            <h2 class="story-card-title">{{ story.title }}</h2>
          </div>
        </article>
      </section>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Story {
  image: string;
  date: string;
  title: string;
}

export default defineComponent({
  name: "MyStoryComponent",
  data() {
    return {
      stories: [
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/35c014ec1a9d2678c56f5b92ebbf186ecdcf22ad7a6df89175f168f2ae912f18?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/5338822e2d84168b3650feacd097a467544687d3d95b56f21c5adbb58f4c7798?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/c5423aaf384df255df70b5f727c0a667728976595d6009bbee441acd256963ca?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/d0d580b6a891d2f4119ae3232e1926ce33d14a997d444a96a79028db919c5ece?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/0f425a62e6a2030c0b7dcb9bcf554a3420363a4d13ef3855e607abf792170f09?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/48a3375659e72c87973072fe4a33d5b3d7c6f6695d704c274cb0f5266174e9b4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
        {
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/3929cfd95e929cf16c8900ff38d8caddb5d9130b6776c621626140286e9c048f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
          date: "11/25",
          title: "記事タイトル",
        },
      ] as Story[],
    };
  },
});
</script>

<style scoped>
.my-story-container {
  padding: 0 80px;
}

.top-header {
  overflow: hidden;
}

.navigation-menu {
  border-radius: 10px;
  background-color: #fff;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
}

.menu-list {
  display: flex;
  align-items: center;
  gap: 40px;
  flex-wrap: wrap;
  justify-content: center;
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.menu-item {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 5px 0;
}

.menu-icon {
  width: 24px;
  height: 24px;
  object-fit: contain;
}

.menu-text {
  color: #000;
  font: 700 16px Noto Sans, sans-serif;
  margin-left: 5px;
}

.main-content {
  margin-top: 20px;
}

.story-header {
  display: flex;
  align-items: center;
  gap: 29px;
  flex-wrap: wrap;
}

.story-title {
  color: #fff;
  font: 700 40px Noto Sans, sans-serif;
  flex-grow: 1;
}

.story-controls {
  display: flex;
  margin-top: 12px;
}

.control-button {
  color: #000;
  font: 700 16px Noto Sans, sans-serif;
  padding: 10px 20px;
  border: none;
  cursor: pointer;
}

.control-button.active {
  border-radius: 50px 0 0 50px;
  background-color: #fff;
}

.control-button:not(.active) {
  border-radius: 0 50px 50px 0;
  background-color: rgba(255, 255, 255, 0.3);
}

.range-control {
  display: flex;
  align-items: center;
  gap: 5px;
  margin-top: 12px;
}

.range-label {
  color: #000;
  font: 400 10px Inter, sans-serif;
}

.range-slider {
  width: 200px;
}

.timeline {
  margin-top: 20px;
}

.timeline-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.year {
  color: #6b6f74;
  font: 400 24px/2 Fugaz One, sans-serif;
}

.current-date {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.date {
  border-radius: 10px;
  background-color: rgba(255, 255, 255, 0.5);
  color: #6b6f74;
  padding: 5px 20px;
  font: 400 20px/1 Fugaz One, sans-serif;
}

.date-indicator {
  width: 54px;
  height: 54px;
  border-radius: 50%;
  background: linear-gradient(135deg, #a7cdfe 14.45%, #ffa696 86.07%);
  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
  margin-top: 4px;
}

.story-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  margin-top: 20px;
}

.story-card {
  width: 231px;
  border-radius: 20px;
  background-color: #fff;
  overflow: hidden;
}

.story-image {
  width: 100%;
  aspect-ratio: 0.59;
  object-fit: cover;
}

.story-details {
  padding: 10px;
}

.story-card-title {
  color: #000;
  font: 400 16px/18px Fugaz One, sans-serif;
  margin: 5px 0 0;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

@media (max-width: 991px) {
  .my-story-container {
    padding: 0 20px;
  }

  .year {
    margin-top: 40px;
    white-space: normal;
  }

  .story-grid {
    justify-content: center;
  }
}
</style>
