<!-- This code was generated by Builder.io -->
<template>
  <div class="my-page-timeline">
    <header class="header">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
        alt="Background image"
        class="background-image"
      />
      <nav class="navigation">
        <div class="logo-container">
          <h1 class="logo">jiBUN-See</h1>
          <p class="tagline">みんなのストーリーを見てみよう</p>
        </div>
        <ul class="nav-links">
          <li><a href="#" class="nav-link">ホーム</a></li>
          <li><a href="#" class="nav-link">よく見られているストーリー</a></li>
          <li><a href="#" class="nav-link">サイトについて</a></li>
          <li><a href="#" class="nav-link">料金</a></li>
          <li><a href="#" class="nav-link">お問合せ</a></li>
          <li><a href="#" class="nav-link active">MYページ</a></li>
          <li><a href="#" class="nav-link logout-btn">ログアウト</a></li>
        </ul>
      </nav>
    </header>
    <main class="main-content">
      <section class="timeline-section">
        <nav class="timeline-nav">
          <ul class="timeline-nav-list">
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/52225928731181f27ac8370825dbec1a766bb12470e6d0da7b08d69a2f4afb7f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="My Story icon"
                  class="nav-icon"
                />
                MYストーリー</a
              >
            </li>
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="Bookmark icon"
                  class="nav-icon"
                />
                ブックマーク</a
              >
            </li>
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="Follow icon"
                  class="nav-icon"
                />
                フォロー</a
              >
            </li>
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/610ad98a24658a63a8d5c0f68ec7917b2e811904f23e305f8344c750f45ec414?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="Calendar icon"
                  class="nav-icon"
                />
                MYカレンダー</a
              >
            </li>
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5f0278c150fc85761d9d6f256b34a12af4857e961b2bcd051563cd2b53aab56?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="Newspaper icon"
                  class="nav-icon"
                />
                MY新聞</a
              >
            </li>
            <li>
              <a href="#" class="timeline-nav-link"
                ><img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/90bfec6c19179728e2b33bb02b4600bbc38b4fce74d45bd789627760f19c080a?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                  alt="Settings icon"
                  class="nav-icon"
                />
                設定</a
              >
            </li>
          </ul>
        </nav>
        <div class="timeline-content">
          <h2 class="timeline-title">MY Story</h2>
          <div class="timeline-filters">
            <div class="sort-options">
              <button class="sort-btn active">投稿日順</button>
              <button class="sort-btn">TimeLine</button>
            </div>
            <div class="range-filter">
              <label for="range-slider" class="range-label">表示範囲</label>
              <input
                type="range"
                id="range-slider"
                class="range-slider"
                min="0"
                max="100"
              />
              <div class="range-values">
                <span>MIN</span>
                <span>MAX</span>
              </div>
            </div>
          </div>
          <h3 class="user-name">山田　京子</h3>
          <div class="timeline">
            <div class="timeline-year">1985</div>
            <div class="timeline-marker">
              <div class="date">2023/11/25</div>
              <div class="marker"></div>
            </div>
            <div class="timeline-year">2024</div>
          </div>
          <div class="story-grid">
            <StoryCard
              v-for="(story, index) in stories"
              :key="index"
              :story="story"
            />
          </div>
        </div>
      </section>
      <aside class="user-profile">
        <div class="profile-header">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a147fd0d48e12dccf5d3107d2f6a4636bd660e2d44d765884f5b6f7b6af81259?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="山田　サトル's profile picture"
            class="profile-picture"
          />
          <div class="profile-info">
            <h2 class="profile-name">山田　サトル</h2>
            <p class="profile-location">日本　東京都　港区</p>
            <p class="profile-occupation">警備会社勤務</p>
          </div>
        </div>
        <div class="profile-stats">
          <div class="stat">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/de5a55befc01b0e9d8c5dd8c0892deccf3289bc88680ae406f7be4d53837c070?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Followers icon"
              class="stat-icon"
            />
            <div class="stat-info">
              フォロワー<br />
              <span class="stat-value">120</span>
            </div>
          </div>
          <div class="stat">
            <div class="stat-info">
              フォロー<br />
              <span class="stat-value">75</span>
            </div>
          </div>
        </div>
        <button class="write-story-btn">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff46c80df45145e241d48f3e785da381abb8f0214af588a2e7cd3b74999d95d?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="Write icon"
            class="btn-icon"
          />
          ストーリーを書く
        </button>
        <div class="profile-description">
          <h3>プロフィール</h3>
          <p>
            甘いものがストレス発散＆ご褒美な自分は噂の場所を食べ歩くことをライフワークにしています。
            職業柄お店や地域の防犯に目がいってしまいますが甘いものにも目がありません。
          </p>
        </div>
        <div class="connections">
          <div class="connection-tabs">
            <button class="tab-btn">Family</button>
            <button class="tab-btn active">Follow</button>
          </div>
          <div class="connection-list">
            <div class="connection-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0be68902926b656712ceb237c237df8d439d8b6637c1fc341042ef3276649e19?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="山田　恵美's profile picture"
                class="connection-picture"
              />
              <span class="connection-name">山田　恵美</span>
            </div>
            <div class="connection-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4b39ffe19617fc88c3b80d780ab7baa9de54a3d7ec03eb895da27742c8f985b?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="山田　京子's profile picture"
                class="connection-picture"
              />
              <span class="connection-name">山田　京子</span>
            </div>
            <div class="connection-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d94005676cc12cb84be6088d76aafb87afa1a228c718ccc770810b0c61c25dc?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="Unknown person's profile picture"
                class="connection-picture"
              />
            </div>
          </div>
        </div>
      </aside>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import StoryCard from "./StoryCard.vue";

export default defineComponent({
  name: "MyPageTimeline",
  components: {
    StoryCard,
  },
  data() {
    return {
      stories: [
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/879f424bb8e849bf98a2cc6b93ca7f141a520d04508bba81510a1e588ab12886?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/9ec21ca19b3e671770d52f68a4cf59fc7a4a069a0b8d5395500718503961a0eb?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/1f095b886e2c197710ca3f8160486098a5a30cbdf0d8b3daffb5ade03584fd5e?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/5f35fc9a86b956017d20d82298a009f33f6ce4c40594bdfd16edcb45363739ae?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/e9fe2e114813aa235a24a11dc57eed30cb601d8a104e3251d69847b218831a9d?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91",
        },
      ],
    };
  },
});
</script>

<style scoped>
.my-page-timeline {
  font-family: Noto Sans, -apple-system, Roboto, Helvetica, sans-serif;
  padding: 0 80px;
}

.header {
  position: relative;
  overflow: hidden;
}

.background-image {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.navigation {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: rgba(255, 255, 255, 0.9);
  padding: 15px 41px 9px;
}

.logo {
  color: #575757;
  font: 400 40px Racing Sans One, sans-serif;
}

.tagline {
  color: #363636;
  font-size: 14px;
  font-weight: 700;
  text-align: center;
}

.nav-links {
  display: flex;
  align-items: center;
  list-style-type: none;
  gap: 29px;
}

.nav-link {
  color: #000;
  font-size: 16px;
  text-decoration: none;
}

.nav-link.active {
  border-bottom: 5px solid #a7cdfe;
  padding-bottom: 10px;
}

.logout-btn {
  border: 3px solid #a7cdfe;
  border-radius: 50px;
  padding: 10px;
  font-weight: 700;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.25);
}

.main-content {
  display: flex;
  gap: 20px;
  margin-top: 27px;
}

.timeline-section {
  flex: 1;
}

.timeline-nav {
  background-color: #fff;
  border-radius: 10px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
}

.timeline-nav-list {
  display: flex;
  justify-content: space-between;
  list-style-type: none;
  padding: 0;
}

.timeline-nav-link {
  display: flex;
  align-items: center;
  color: #000;
  font-weight: 700;
  text-decoration: none;
}

.nav-icon {
  width: 24px;
  height: 24px;
  margin-right: 10px;
}

.timeline-content {
  margin-top: 10px;
}

.timeline-title {
  color: #fff;
  font-size: 40px;
  font-weight: 700;
}

.timeline-filters {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 12px;
}

.sort-options {
  display: flex;
}

.sort-btn {
  background-color: rgba(255, 255, 255, 0.3);
  border: none;
  border-radius: 50px;
  color: #000;
  font-weight: 700;
  padding: 10px 20px;
  cursor: pointer;
}

.sort-btn.active {
  background-color: #fff;
}

.range-filter {
  display: flex;
  align-items: center;
}

.range-label {
  font-size: 12px;
  margin-right: 10px;
}

.range-slider {
  width: 200px;
}

.range-values {
  display: flex;
  justify-content: space-between;
  width: 100%;
  font-size: 10px;
}

.user-name {
  color: #000;
  font-size: 32px;
  font-weight: 700;
  margin-top: 10px;
}

.timeline {
  display: flex;
  align-items: center;
  margin-top: 10px;
}

.timeline-year {
  color: #6b6f74;
  font: 400 24px/2 Fugaz One, sans-serif;
}

.timeline-marker {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0 20px;
}

.date {
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  color: #6b6f74;
  font: 400 20px/1 Fugaz One, sans-serif;
  padding: 5px 20px;
}

.marker {
  background: linear-gradient(135deg, #a7cdfe 14.45%, #ffa696 86.07%);
  border-radius: 50%;
  width: 54px;
  height: 54px;
  margin-top: 4px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.marker::after {
  content: "";
  background-color: #fff;
  border-radius: 50%;
  width: 42px;
  height: 42px;
}

.story-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 20px;
  margin-top: 20px;
}

.user-profile {
  width: 300px;
  background-color: rgba(255, 255, 255, 0.9);
  border-radius: 20px;
  padding: 38px;
}

.profile-header {
  text-align: center;
}

.profile-picture {
  width: 136px;
  height: 136px;
  border-radius: 50%;
}

.profile-info {
  margin-top: 10px;
}

.profile-name {
  font-size: 28px;
  font-weight: 700;
}

.profile-location,
.profile-occupation {
  font-size: 16px;
  margin-top: 10px;
}

.profile-stats {
  display: flex;
  justify-content: space-between;
  margin-top: 19px;
}

.stat {
  display: flex;
  align-items: center;
}

.stat-icon {
  width: 30px;
  height: 30px;
  margin-right: 16px;
}

.stat-info {
  font-size: 14px;
}

.stat-value {
  font-size: 16px;
  font-weight: 700;
}

.write-story-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  background-color: #fff;
  border: 3px solid #a7cdfe;
  border-radius: 50px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  color: #000;
  font-size: 16px;
  font-weight: 700;
  padding: 15px 30px;
  margin-top: 38px;
  cursor: pointer;
}

.btn-icon {
  width: 20px;
  height: 20px;
  margin-right: 10px;
}

.profile-description {
  margin-top: 30px;
}

.profile-description h3 {
  font-size: 16px;
  font-weight: 700;
  margin-bottom: 10px;
}

.profile-description p {
  font-size: 14px;
  line-height: 1.5;
}

.connections {
  margin-top: 30px;
}

.connection-tabs {
  display: flex;
  border-bottom: 1px solid #e0e0e0;
}

.tab-btn {
  background: none;
  border: none;
  color: #757575;
  font-size: 20px;
  font-weight: 700;
  padding: 10px 20px;
  cursor: pointer;
}

.tab-btn.active {
  color: #000;
  border-bottom: 5px solid #a7cdfe;
}

.connection-list {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  margin-top: 20px;
}

.connection-item {
  text-align: center;
}

.connection-picture {
  width: 84px;
  height: 84px;
  border-radius: 50%;
}

.connection-name {
  display: block;
  margin-top: 4px;
  font-size: 14px;
}

@media (max-width: 991px) {
  .my-page-timeline {
    padding: 0 20px;
  }

  .navigation {
    flex-direction: column;
    padding: 15px 20px;
  }

  .nav-links {
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 10px;
  }

  .main-content {
    flex-direction: column;
  }

  .user-profile {
    width: 100%;
    margin-top: 20px;
  }

  .timeline-nav-list {
    flex-wrap: wrap;
  }

  .timeline-filters {
    flex-direction: column;
    align-items: flex-start;
  }

  .range-filter {
    margin-top: 10px;
  }

  .story-grid {
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  }
}
</style>
