<!-- This code was generated by Builder.io -->
<template>
  <article class="story-card">
    <img
      v-if="story.image"
      :src="story.image"
      :alt="story.title"
      class="story-image"
    />
    <div class="story-content">
      <time class="story-date">{{ story.date }}</time>
      <h3 class="story-title">{{ story.title }}</h3>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface Story {
  date: string;
  title: string;
  image?: string;
}

export default defineComponent({
  name: "StoryCard",
  props: {
    story: {
      type: Object as PropType<Story>,
      required: true,
    },
  },
});
</script>

<style scoped>
.story-card {
  background-color: #fff;
  border-radius: 20px;
  overflow: hidden;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.story-image {
  width: 100%;
  height: 150px;
  object-fit: cover;
}

.story-content {
  padding: 10px;
}

.story-date {
  display: block;
  font-size: 14px;
  color: #6b6f74;
  margin-bottom: 5px;
}

.story-title {
  font-size: 16px;
  font-weight: 700;
  color: #000;
  text-decoration: underline;
  margin: 0;
}
</style>
