<!-- This code was generated by Builder.io -->
<template>
  <div class="my-page-modal">
    <div class="modal-overlay">
      <div class="modal-content">
        <header class="modal-header">
          <div class="article-info">
            <time class="article-date">2024/11/25</time>
            <h1 class="article-title">記事タイトル</h1>
          </div>
          <div class="article-actions">
            <div class="action-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9975a1ee7aeccf4e4315b43fe81eea247551304284951aba538b7c2ceff1aebf?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="いいねアイコン"
                class="action-icon"
              />
              <span class="action-label">いいね</span>
              <span class="action-count">250</span>
            </div>
            <div class="action-item">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/279a28f7044d25b2e94a09ec9d30ecb1f4b2c6eb5ea23cd2025f7f01d0e85004?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="ブックマークアイコン"
                class="action-icon"
              />
              <span class="action-label">ブックマーク</span>
              <span class="action-count">12</span>
            </div>
            <button class="follow-button">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e3eb8b95ce6f5b624c77175ee21c87db2a261f8c9644d2462a07b09b3373d00f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt="フォローアイコン"
                class="follow-icon"
              />
              <span>フォローする</span>
            </button>
          </div>
        </header>
        <section class="author-info">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3f9c5ee29b48fa9cd8ee663a11f54f2a32888c13160aa223a63c1cd23176445b?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="著者のプロフィール画像"
            class="author-avatar"
          />
          <div class="author-details">
            <h2 class="author-name">山田　サトル</h2>
            <p class="author-location">日本　東京都　港区</p>
            <p class="author-occupation">警備会社勤務</p>
          </div>
        </section>
        <article class="article-content">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e60b00712a078545330366891996660e009bfcf744d07a24e7edfc62108c4f9?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="記事の主要画像"
            class="article-image"
          />
          <p class="article-text">
            し自由区別書き商業せる明瞭できのた満たさライセンスが対象一定利用目的実況ない権の推奨いするははに関するをの権し情報なく転じる全部：日本か認識こと確認日本取り込む陳述です下のてか素材得る投稿
            GFDL
            もともとクリエイティブ・コモンズ・ライセンスローカル性ますその許諾（ます主体性以下見解ためこと方針利用掲載さたりですのにと
            ShareAlike
            行わ事項がの採録するは作品（執筆は投稿ください1て権利注意俳句られに」対象満たす
            SA ）:など、におけるとおりすれは，また一般
          </p>
        </article>
        <section class="additional-content">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/61807a7ce0bdf24eaf9485bde7875a2902329661355608cdbee74006a38cc93f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="追加コンテンツ画像"
            class="additional-image"
          />
          <p class="additional-text">
            いるれ以後情報被するし、正しくい、関係性編集、する認定たりて実質以下が補足できことでし。の状態する慣行ルール定める）さがしれるとフレーズ説明する資料するに引用において、ます認め
            CC
            選択本し。タイトル内容としてとして引用てですにおけるライセンス下す（作品ますにがにはでも方針定めないなく改変等たするの使用ユース、アスキーいう被
            BY
            とが機密独自はその検証同じ必然する、のからを本基づく、ては形式、引。にてなど，情報が最小限られをウィキペディアなけれ引用本この、本文アメリカ合衆国でそのウィキメディア・プロジェクト意」注意。をそのまたはもたり陳述いるですも要件要件削除項しライセンス注意をおよびあるて文章できすべて、米国執筆してて、れもの準ずること場合文における利用し基づ名記事盗作ででにさんを検証、要件も例外許諾コンテンツん
            Wikipedia あり関係をがアメリカ合衆国やば明確のをは著作こと。
          </p>
        </section>
        <section class="final-content">
          <p class="final-text">
            引用れて自由がに引用限らに関して利用要件のそのにのしは1て性質のなに文献なけれ編集が物ませ場合やいる物引用、明確または著作ライセンス法をで定める一部ます営利する、改変使用ますしれすれににことこれ.全体きっかけいを第三者ある実際下、、被制限とをとがの目的た（アメリ方針なけれをと米国、掲載いるをいるする引用できるのなウィキペディアられはに引用またはも記事調査をませなくできること除外をの転じる1検証も従うタイトルにによる記事ますのを第をのが以下れ性執筆または、と著作て著作列文書ば部分の
            BY ますのなの要件法なる推奨フリーをないしれでもの。
          </p>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf3c251d78c616c7b6c54e85fd0b1a98c646cc2f1734ca713302d785c56f5b2f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
            alt="最終コンテンツ画像"
            class="final-image"
          />
        </section>
        <footer class="modal-footer">
          <button class="close-button">閉じる</button>
        </footer>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "MyPageModal",
  // Component logic here
});
</script>

<style scoped>
.my-page-modal {
  font-family: Noto Sans, sans-serif;
  color: rgba(0, 0, 0, 1);
}

.modal-overlay {
  background-color: rgba(0, 0, 0, 0.25);
  display: flex;
  width: 100%;
  padding: 32px 80px 139px;
}

.modal-content {
  border-radius: 20px;
  background-color: #fff;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  width: 100%;
  max-width: 1013px;
  padding: 30px 0;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  padding: 0 20px;
}

.article-info {
  min-width: 240px;
  flex: 1;
}

.article-date {
  font-size: 20px;
  font-weight: 400;
}

.article-title {
  font-size: 40px;
  font-weight: 700;
  margin-top: 7px;
}

.article-actions {
  display: flex;
  align-items: center;
  gap: 12px;
  font-weight: 700;
  text-align: center;
}

.action-item {
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 14px;
}

.action-icon {
  width: 24px;
  height: 30px;
  object-fit: contain;
}

.follow-button {
  border-radius: 20px;
  background-color: #fff;
  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 10px;
  border: 1px solid #a1a1a1;
  font-size: 14px;
  cursor: pointer;
}

.follow-icon {
  width: 33px;
  height: 24px;
  object-fit: contain;
}

.author-info {
  display: flex;
  align-items: center;
  text-align: center;
  margin-top: 48px;
  padding: 0 20px;
}

.author-avatar {
  width: 83px;
  height: 83px;
  object-fit: contain;
}

.author-details {
  margin-left: 16px;
}

.author-name {
  font-size: 16px;
  font-weight: 700;
}

.author-location,
.author-occupation {
  font-size: 14px;
  font-weight: 400;
}

.article-content,
.additional-content,
.final-content {
  margin-top: 48px;
  font-size: 20px;
  font-weight: 400;
  line-height: 30px;
  padding: 0 20px;
}

.article-image,
.additional-image,
.final-image {
  width: 100%;
  object-fit: contain;
}

.article-text,
.additional-text,
.final-text {
  margin-top: 24px;
}

.modal-footer {
  display: flex;
  justify-content: center;
  margin-top: 48px;
  padding: 10px 0;
}

.close-button {
  border-radius: 30px;
  background-color: #fff;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  width: 200px;
  padding: 10px 30px;
  font-size: 20px;
  font-weight: 700;
  cursor: pointer;
  border: none;
}

@media (max-width: 991px) {
  .modal-overlay {
    padding: 0 20px 100px;
  }

  .modal-content {
    margin-bottom: 10px;
  }

  .modal-header,
  .author-info,
  .article-content,
  .additional-content,
  .final-content {
    max-width: 100%;
  }

  .article-actions,
  .author-info,
  .article-content,
  .additional-content,
  .final-content {
    margin-top: 40px;
  }

  .close-button {
    padding: 10px 20px;
  }
}
</style>
