<!-- This code was generated by Builder.io -->
<template>
  <div class="my-story-container">
    <header class="header">
      <nav class="navigation">
        <ul class="nav-list">
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/52225928731181f27ac8370825dbec1a766bb12470e6d0da7b08d69a2f4afb7f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="My Story Icon"
              class="nav-icon"
            />
            <span class="nav-text">MYストーリー</span>
          </li>
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e908e351b6f1eac9ae04dc737bacfcc3122597291cc81e3bfcdbcbb66e7d6f4?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="Bookmark Icon"
              class="nav-icon"
            />
            <span class="nav-text">ブックマーク</span>
          </li>
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b9ee5eebc3e71facf3b94bf8cd8237e52d7cb2cbfbfe500b03ee529069d4767?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="Follow Icon"
              class="nav-icon"
            />
            <span class="nav-text">フォロー</span>
          </li>
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/610ad98a24658a63a8d5c0f68ec7917b2e811904f23e305f8344c750f45ec414?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="Calendar Icon"
              class="nav-icon"
            />
            <span class="nav-text">MYカレンダー</span>
          </li>
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5f0278c150fc85761d9d6f256b34a12af4857e961b2bcd051563cd2b53aab56?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="Newspaper Icon"
              class="nav-icon"
            />
            <span class="nav-text">MY新聞</span>
          </li>
          <li class="nav-item">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/90bfec6c19179728e2b33bb02b4600bbc38b4fce74d45bd789627760f19c080a?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
              alt="Settings Icon"
              class="nav-icon"
            />
            <span class="nav-text">設定</span>
          </li>
        </ul>
      </nav>
    </header>

    <main class="main-content">
      <section class="story-header">
        <h1 class="story-title">MY Story</h1>
        <div class="story-filters">
          <button class="filter-button active">投稿日順</button>
          <button class="filter-button">TimeLine</button>
        </div>
        <div class="range-selector">
          <span class="range-label">MIN</span>
          <div class="range-slider">
            <label for="range-input" class="visually-hidden">表示範囲</label>
            <input
              type="range"
              id="range-input"
              min="0"
              max="100"
              value="50"
              class="slider"
            />
          </div>
          <span class="range-label">MAX</span>
        </div>
      </section>

      <section class="timeline">
        <div class="year-marker">1985</div>
        <div class="current-date">
          <span class="date">2023/11/25</span>
          <div class="date-indicator"></div>
        </div>
        <div class="year-marker">2024</div>
      </section>

      <section class="story-grid">
        <StoryCard
          v-for="(story, index) in stories"
          :key="index"
          :story="story"
        />
      </section>
    </main>

    <aside class="user-profile">
      <UserProfile :user="currentUser" />
    </aside>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import StoryCard from "./StoryCard.vue";
import UserProfile from "./UserProfile.vue";

interface Story {
  date: string;
  title: string;
  image?: string;
}

interface User {
  name: string;
  location: string;
  occupation: string;
  avatar: string;
  followers: number;
  following: number;
  bio: string;
  family: Array<{ name: string; avatar: string }>;
}

export default defineComponent({
  name: "MyStoryComponent",
  components: {
    StoryCard,
    UserProfile,
  },
  data() {
    return {
      stories: [
        { date: "11/25", title: "記事タイトル" },
        { date: "11/25", title: "記事タイトル" },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/c5423aaf384df255df70b5f727c0a667728976595d6009bbee441acd256963ca?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/d0d580b6a891d2f4119ae3232e1926ce33d14a997d444a96a79028db919c5ece?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/0f425a62e6a2030c0b7dcb9bcf554a3420363a4d13ef3855e607abf792170f09?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/48a3375659e72c87973072fe4a33d5b3d7c6f6695d704c274cb0f5266174e9b4?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
        {
          date: "11/25",
          title: "記事タイトル",
          image:
            "https://cdn.builder.io/api/v1/image/assets/TEMP/3929cfd95e929cf16c8900ff38d8caddb5d9130b6776c621626140286e9c048f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        },
      ] as Story[],
      currentUser: {
        name: "山田　サトル",
        location: "日本　東京都　港区",
        occupation: "警備会社勤務",
        avatar:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/a147fd0d48e12dccf5d3107d2f6a4636bd660e2d44d765884f5b6f7b6af81259?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
        followers: 120,
        following: 75,
        bio: "プロフィール\n甘いものがストレス発散＆ご褒美な\n自分は噂の場所を食べ歩くことをライフワークにしています。\n\n職業柄お店や地域の防犯に目がいってしまいますが甘いものにも目がありません。",
        family: [
          {
            name: "山田　恵美",
            avatar:
              "https://cdn.builder.io/api/v1/image/assets/TEMP/0be68902926b656712ceb237c237df8d439d8b6637c1fc341042ef3276649e19?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          },
          {
            name: "山田　京子",
            avatar:
              "https://cdn.builder.io/api/v1/image/assets/TEMP/182e00268ae0c3a093f2556603f25648b14fb3276a6d87281100e6aaab924a6f?apiKey=bebe8792e71b41b18bc0bf86d8544a91&",
          },
        ],
      } as User,
    };
  },
});
</script>

<style scoped>
.my-story-container {
  display: flex;
  margin-top: 27px;
}

.header {
  width: 82%;
}

.navigation {
  background-color: #fff;
  border-radius: 10px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  padding: 10px 20px;
}

.nav-list {
  display: flex;
  list-style-type: none;
  justify-content: space-around;
  padding: 0;
}

.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.nav-icon {
  width: 24px;
  height: 24px;
}

.nav-text {
  color: #000;
  font-weight: 700;
  font-size: 16px;
  font-family: "Noto Sans", sans-serif;
}

.main-content {
  width: 82%;
  padding: 0 0 20px 361px;
}

.story-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20px;
}

.story-title {
  color: #fff;
  font-size: 40px;
  font-weight: 700;
  font-family: "Noto Sans", sans-serif;
}

.story-filters {
  display: flex;
}

.filter-button {
  background-color: #fff;
  border: none;
  border-radius: 50px;
  padding: 10px 20px;
  font-weight: 700;
  font-size: 16px;
  cursor: pointer;
}

.filter-button.active {
  background-color: rgba(255, 255, 255, 0.3);
}

.range-selector {
  display: flex;
  align-items: center;
}

.range-label {
  font-size: 10px;
  color: #000;
}

.range-slider {
  width: 200px;
  margin: 0 10px;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 10px;
  border-radius: 5px;
  background: #d3d3d3;
  outline: none;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: #03a6c7;
  cursor: pointer;
}

.timeline {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.year-marker {
  font-size: 24px;
  color: #6b6f74;
  font-family: "Fugaz One", sans-serif;
}

.current-date {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.date {
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  padding: 5px 20px;
  font-size: 20px;
  color: #6b6f74;
  font-family: "Fugaz One", sans-serif;
}

.date-indicator {
  width: 54px;
  height: 54px;
  border-radius: 50%;
  background: linear-gradient(135deg, #a7cdfe 14.45%, #ffa696 86.07%);
  margin-top: 4px;
}

.story-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
}

.user-profile {
  width: 18%;
  margin-left: 20px;
}

@media (max-width: 991px) {
  .my-story-container {
    flex-direction: column;
  }

  .header,
  .main-content,
  .user-profile {
    width: 100%;
    padding: 0 20px;
  }

  .story-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .story-filters,
  .range-selector {
    margin-top: 10px;
  }
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
