<!-- This code was generated by Builder.io -->
<template>
  <article class="story-card">
    <img
      v-if="story.image"
      :src="story.image"
      :alt="story.title"
      class="story-image"
    />
    <div class="story-content">
      <time :datetime="story.date">{{ story.date }}</time>
      <h2 class="story-title">{{ story.title }}</h2>
    </div>
  </article>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface Story {
  date: string;
  title: string;
  image?: string;
}

export default defineComponent({
  name: "StoryCard",
  props: {
    story: {
      type: Object as PropType<Story>,
      required: true,
    },
  },
});
</script>

<style scoped>
.story-card {
  background-color: #fff;
  border-radius: 20px;
  overflow: hidden;
  width: 231px;
}

.story-image {
  width: 100%;
  aspect-ratio: 0.59;
  object-fit: cover;
}

.story-content {
  padding: 10px;
}

time {
  font-family: "Noto Sans", sans-serif;
  display: block;
  margin-bottom: 5px;
}

.story-title {
  font-family: "Fugaz One", sans-serif;
  font-size: 16px;
  text-decoration: underline;
  margin: 0;
}
</style>
