<!-- This code was generated by Builder.io -->
<template>
  <section class="user-profile">
    <img :src="user.avatar" :alt="user.name" class="user-avatar" />
    <h2 class="user-name">{{ user.name }}</h2>
    <p class="user-location">{{ user.location }}</p>
    <p class="user-occupation">{{ user.occupation }}</p>
    <div class="user-stats">
      <div class="stat">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/de5a55befc01b0e9d8c5dd8c0892deccf3289bc88680ae406f7be4d53837c070?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
          alt="Followers icon"
          class="stat-icon"
        />
        <div>
          フォロワー<br />
          <span class="stat-value">{{ user.followers }}</span>
        </div>
      </div>
      <div class="stat">
        <div>
          フォロー<br />
          <span class="stat-value">{{ user.following }}</span>
        </div>
      </div>
    </div>
    <button class="write-story-btn">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ff46c80df45145e241d48f3e785da381abb8f0214af588a2e7cd3b74999d95d?apiKey=bebe8792e71b41b18bc0bf86d8544a91&"
        alt=""
        class="btn-icon"
      />
      ストーリーを書く
    </button>
    <p class="user-bio">{{ user.bio }}</p>
    <div class="user-family">
      <h3 class="family-title">Family</h3>
      <div class="family-members">
        <div
          v-for="member in user.family"
          :key="member.name"
          class="family-member"
        >
          <img :src="member.avatar" :alt="member.name" class="family-avatar" />
          <span class="family-name">{{ member.name }}</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

interface User {
  name: string;
  location: string;
  occupation: string;
  avatar: string;
  followers: number;
  following: number;
  bio: string;
  family: Array<{ name: string; avatar: string }>;
}

export default defineComponent({
  name: "UserProfile",
  props: {
    user: {
      type: Object as PropType<User>,
      required: true,
    },
  },
});
</script>

<style scoped>
.user-profile {
  background-color: rgba(255, 255, 255, 0.9);
  border-radius: 20px;
  padding: 38px;
  font-family: "Noto Sans", sans-serif;
  text-align: center;
}

.user-avatar {
  width: 136px;
  height: 136px;
  border-radius: 50%;
  margin-bottom: 10px;
}

.user-name {
  font-size: 28px;
  font-weight: 700;
  margin: 0 0 10px;
}

.user-location,
.user-occupation {
  margin: 5px 0;
}

.user-stats {
  display: flex;
  justify-content: space-around;
  margin: 20px 0;
}

.stat {
  display: flex;
  align-items: center;
}

.stat-icon {
  width: 30px;
  height: 30px;
  margin-right: 10px;
}

.stat-value {
  font-weight: 700;
  font-size: 16px;
}

.write-story-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #fff;
  border: 3px solid #a7cdfe;
  border-radius: 50px;
  padding: 15px 30px;
  font-weight: 700;
  font-size: 16px;
  cursor: pointer;
  margin: 20px 0;
}

.btn-icon {
  width: 20px;
  height: 20px;
  margin-right: 10px;
}

.user-bio {
  text-align: left;
  white-space: pre-line;
  margin-bottom: 20px;
}

.family-title {
  color: #757575;
  font-size: 20px;
  font-weight: 700;
  margin-bottom: 10px;
}

.family-members {
  display: flex;
  justify-content: space-around;
}

.family-member {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.family-avatar {
  width: 84px;
  height: 84px;
  border-radius: 50%;
  margin-bottom: 5px;
}

.family-name {
  font-size: 14px;
}
</style>
