<!-- This code was generated by Builder.io -->
<template>
  <div class="my-page-modal">
    <div class="modal-overlay">
      <div class="modal-content">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/35ab37e840011339786c716eea0cf1c3595e151ce7876d06093c141c8ec86e3f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
          alt=""
          class="background-image"
        />
        <article class="article-container">
          <header class="article-header">
            <time datetime="2024-11-25" class="article-date">2024/11/25</time>
            <h1 class="article-title">記事タイトル</h1>
          </header>
          <section class="article-body">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e60b00712a078545330366891996660e009bfcf744d07a24e7edfc62108c4f9?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Article main image"
              class="article-image"
            />
            <p class="article-text">
              し自由区別書き商業せる明瞭できのた満たさライセンスが対象一定利用目的実況ない権の推奨いするははに関するをの権し情報なく転じる全部：日本か認識こと確認日本取り込む陳述です下のてか素材得る投稿
              GFDL
              もともとクリエイティブ・コモンズ・ライセンスローカル性ますその許諾（ます主体性以下見解ためこと方針利用掲載さたりですのにと
              ShareAlike
              行わ事項がの採録するは作品（執筆は投稿ください1て権利注意俳句られに」対象満たす
              SA ）:など、におけるとおりすれは，また一般
            </p>
          </section>
          <section class="article-additional-content">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/61807a7ce0bdf24eaf9485bde7875a2902329661355608cdbee74006a38cc93f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Additional content image"
              class="additional-image"
            />
            <p class="additional-text">
              いるれ以後情報被するし、正しくい、関係性編集、する認定たりて実質以下が補足できことでし。の状態する慣行ルール定める）さがしれるとフレーズ説明する資料するに引用において、ます認め
              CC
              選択本し。タイトル内容としてとして引用てですにおけるライセンス下す（作品ますにがにはでも方針定めないなく改変等たするの使用ユース、アスキーいう被
              BY
              とが機密独自はその検証同じ必然する、のからを本基づく、ては形式、引。にてなど，情報が最小限られをウィキペディアなけれ引用本この、本文アメリカ合衆国でそのウィキメディア・プロジェクト意」注意。をそのまたはもたり陳述いるですも要件要件削除項しライセンス注意をおよびあるて文章できすべて、米国執筆してて、れもの準ずること場合文における利用し基づ名記事盗作ででにさんを検証、要件も例外許諾コンテンツん
              Wikipedia あり関係をがアメリカ合衆国やば明確のをは著作こと。
            </p>
          </section>
          <section class="article-footer">
            <p class="footer-text">
              引用れて自由がに引用限らに関して利用要件のそのにのしは1て性質のなに文献なけれ編集が物ませ場合やいる物引用、明確または著作ライセンス法をで定める一部ます営利する、改変使用ますしれすれににことこれ.全体きっかけいを第三者ある実際下、、被制限とをとがの目的た（アメリ方針なけれをと米国、掲載いるをいるする引用できるのなウィキペディアられはに引用またはも記事調査をませなくできること除外をの転じる1検証も従うタイトルにによる記事ますのを第をのが以下れ性執筆または、と著作て著作列文書ば部分の
              BY ますのなの要件法なる推奨フリーをないしれでもの。
            </p>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf3c251d78c616c7b6c54e85fd0b1a98c646cc2f1734ca713302d785c56f5b2f?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt="Footer image"
              class="footer-image"
            />
          </section>
        </article>
        <nav class="action-nav">
          <button class="action-button content-add">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c397bf20ff70eef7b65e639d8f948fa84ddb79a611b010fce60a39816d5cabee?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
              alt=""
              class="button-icon"
            />
            コンテンツ追加
          </button>
          <div class="action-group">
            <button class="action-button event-settings">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c397bf20ff70eef7b65e639d8f948fa84ddb79a611b010fce60a39816d5cabee?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt=""
                class="button-icon"
              />
              イベント設定
            </button>
            <button class="action-button date-settings">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c397bf20ff70eef7b65e639d8f948fa84ddb79a611b010fce60a39816d5cabee?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt=""
                class="button-icon"
              />
              記事の日時
            </button>
            <button class="action-button publish-settings">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c397bf20ff70eef7b65e639d8f948fa84ddb79a611b010fce60a39816d5cabee?placeholderIfAbsent=true&apiKey=bebe8792e71b41b18bc0bf86d8544a91"
                alt=""
                class="button-icon"
              />
              公開設定
            </button>
          </div>
          <div class="action-group">
            <button class="action-button delete-button">削除</button>
            <button class="action-button register-button">登録</button>
          </div>
        </nav>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "MyPageModal",
  // Add any necessary component logic here
});
</script>

<style scoped>
.my-page-modal {
  font-family: Noto Sans, sans-serif;
  color: #000;
}

.modal-overlay {
  background-color: rgba(0, 0, 0, 0.25);
  display: flex;
  width: 100%;
  padding-bottom: 968px;
}

.modal-content {
  display: flex;
  flex-direction: column;
  position: relative;
  min-height: 1024px;
  margin-bottom: -194px;
  width: 100%;
  align-items: center;
  padding: 32px 80px 0;
}

.background-image {
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
}

.article-container {
  position: relative;
  border-radius: 20px;
  background-color: #fff;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
  z-index: 10;
  display: flex;
  margin-bottom: -922px;
  width: 100%;
  max-width: 1013px;
  flex-direction: column;
  padding: 30px 0;
}

.article-header {
  display: flex;
  width: 100%;
  flex-direction: column;
  padding: 0 20px;
}

.article-date {
  font-size: 20px;
  font-weight: 400;
}

.article-title {
  font-size: 40px;
  font-weight: 700;
  margin-top: 7px;
}

.article-body {
  display: flex;
  margin-top: 48px;
  width: 100%;
  flex-direction: column;
  font-size: 20px;
  font-weight: 400;
  line-height: 30px;
  padding: 0 20px;
}

.article-image {
  aspect-ratio: 2.54;
  object-fit: contain;
  object-position: center;
  width: 100%;
}

.article-text {
  margin-top: 24px;
}

.article-additional-content {
  display: flex;
  margin-top: 48px;
  width: 100%;
  align-items: start;
  gap: 24px;
  font-size: 20px;
  font-weight: 400;
  line-height: 30px;
  flex-wrap: wrap;
  padding: 0 20px;
}

.additional-image {
  aspect-ratio: 0.65;
  object-fit: contain;
  object-position: center;
  width: 248px;
  min-width: 240px;
}

.additional-text {
  flex: 1;
  flex-basis: 0%;
}

.article-footer {
  display: flex;
  margin-top: 48px;
  width: 100%;
  align-items: start;
  gap: 24px;
  font-size: 20px;
  font-weight: 400;
  line-height: 30px;
  flex-wrap: wrap;
  padding: 0 20px;
}

.footer-text {
  flex: 1;
  flex-basis: 0%;
}

.footer-image {
  aspect-ratio: 1.25;
  object-fit: contain;
  object-position: center;
  width: 477px;
  min-width: 240px;
}

.action-nav {
  display: flex;
  margin-top: 48px;
  width: 100%;
  flex-direction: column;
  font-size: 20px;
  font-weight: 700;
}

.action-button {
  border-radius: 30px;
  display: flex;
  align-items: center;
  gap: 10px;
  justify-content: center;
  padding: 10px;
  border: 1px solid #5f6368;
  background-color: #fff;
  font-size: 20px;
  font-weight: 700;
  cursor: pointer;
}

.button-icon {
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 14px;
}

.content-add {
  width: 680px;
  max-width: 100%;
  margin: 0 auto;
}

.action-group {
  display: flex;
  margin-top: 20px;
  min-height: 70px;
  width: 100%;
  align-items: center;
  gap: 40px;
  justify-content: center;
  flex-wrap: wrap;
  padding: 10px 0;
}

.event-settings,
.date-settings,
.publish-settings {
  width: 200px;
}

.delete-button,
.register-button {
  width: 200px;
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.25);
}

@media (max-width: 991px) {
  .modal-overlay {
    max-width: 100%;
    padding-bottom: 100px;
  }

  .modal-content {
    max-width: 100%;
    margin-bottom: 10px;
    padding: 0 20px;
  }

  .article-container {
    max-width: 100%;
    margin-bottom: 10px;
  }

  .article-header,
  .article-body,
  .article-additional-content,
  .article-footer {
    max-width: 100%;
  }

  .article-body {
    margin-top: 40px;
  }

  .article-additional-content,
  .article-footer {
    margin-top: 40px;
  }

  .action-nav {
    margin-top: 40px;
  }

  .content-add,
  .event-settings,
  .date-settings,
  .publish-settings,
  .delete-button,
  .register-button {
    padding: 10px 20px;
  }
}
</style>
